// AUTO-GENERATED by scripts/validate_and_generate.ps1 → registry_generator.js — DO NOT EDIT.
#include "ParameterConversion.gen.h"

#include <cmath>

namespace ABD
{
namespace Registry
{
namespace Conversion
{

namespace
{
    inline float clamp01 (float v) noexcept { return v < 0.0f ? 0.0f : (v > 1.0f ? 1.0f : v); }
    inline float lerp (float a, float b, float t) noexcept { return a + (b - a) * t; }
}

const std::array<Entry, kConversionCount> kConversions = {{
    { "lfo1_rate", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 0, WireCodec::Value, 255, "Hz", 0.035f, 63.281485f, Curve::Exp, 0.035000f, 7.500000f, nullptr, 0, nullptr, 0, Smoothing::Log, 0 },
    { "lfo1_delay", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 1, WireCodec::Value, 255, "s", 0.0f, 6.59f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Log, 1 },
    { "lfo1_shape", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 2, WireCodec::Enum, 6, "index", 0.0f, 6.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 2 },
    { "lfo1_key_sync", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 3, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 3 },
    { "lfo1_arp_sync", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 4, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 4 },
    { "lfo1_mono_mode", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 5, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 5 },
    { "lfo1_slew", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 6, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 6 },
    { "lfo2_rate", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 7, WireCodec::Value, 255, "Hz", 0.035f, 63.281485f, Curve::Exp, 0.035000f, 7.500000f, nullptr, 0, nullptr, 0, Smoothing::Log, 7 },
    { "lfo2_delay", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 8, WireCodec::Value, 255, "s", 0.0f, 6.59f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Log, 8 },
    { "lfo2_shape", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 9, WireCodec::Enum, 6, "index", 0.0f, 6.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 9 },
    { "lfo2_key_sync", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 10, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 10 },
    { "lfo2_arp_sync", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 11, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 11 },
    { "lfo2_mono_mode", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 12, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 12 },
    { "lfo2_slew", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 13, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 13 },
    { "osc1_range", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 14, WireCodec::Enum, 2, "index", 0.0f, 2.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 14 },
    { "osc2_range", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 15, WireCodec::Enum, 2, "index", 0.0f, 2.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 15 },
    { "osc1_pwm_source", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 16, WireCodec::Enum, 5, "index", 0.0f, 5.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 16 },
    { "osc2_pm_source", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 32, WireCodec::Enum, 6, "index", 0.0f, 6.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 17 },
    { "osc2_tpm_source", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 17, WireCodec::Enum, 5, "index", 0.0f, 5.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 18 },
    { "osc1_square_enable", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 18, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 19 },
    { "osc1_saw_enable", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 19, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 20 },
    { "osc_sync_enable", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 20, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 21 },
    { "osc1_pitch_mod", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 21, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 22 },
    { "osc1_pm_source", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 22, WireCodec::Enum, 6, "index", 0.0f, 6.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 23 },
    { "osc1_lfo_aftertouch", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 23, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 24 },
    { "osc1_lfo_modwheel", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 24, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 25 },
    { "osc1_pwm_amount", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 25, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 26 },
    { "osc2_level", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 26, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 27 },
    { "osc2_pitch", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 27, WireCodec::Value, 255, "semitone", -12.0f, 12.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 28 },
    { "osc2_tone_mod", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 28, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 29 },
    { "osc2_pitch_mod", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 29, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 30 },
    { "osc2_aftertouch_pitch", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 30, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 31 },
    { "osc2_modwheel_pitch", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 31, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 32 },
    { "noise_level", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 33, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 33 },
    { "global_portamento", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 34, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Log, 34 },
    { "porta_mode", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 35, WireCodec::Enum, 9, "index", 0.0f, 9.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 35 },
    { "pitch_bend_up", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 36, WireCodec::Value, 255, "semitone", 0.0f, 24.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 36 },
    { "pitch_bend_down", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 37, WireCodec::Value, 255, "semitone", 0.0f, 24.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 37 },
    { "osc1_pm_mode", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 38, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 38 },
    { "vcf_cutoff", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 39, WireCodec::Value, 255, "Hz", 15.0f, 8250.0f, Curve::Exp, 15.000000f, 6.309918f, nullptr, 0, nullptr, 0, Smoothing::Log, 39 },
    { "hpf_cutoff", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 40, WireCodec::Value, 255, "Hz", 20.0f, 2000.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Log, 40 },
    { "vcf_resonance", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 41, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 41 },
    { "vcf_env_depth", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 42, WireCodec::Bipolar, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 42 },
    { "vcf_env_vel", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 43, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 43 },
    { "vcf_pitch_bend", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 44, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 44 },
    { "vcf_lfo_depth", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 45, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 45 },
    { "vcf_lfo_select", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 46, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 46 },
    { "vcf_aftertouch_lfo", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 47, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 47 },
    { "vcf_modwheel_lfo", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 48, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 48 },
    { "vcf_key_tracking", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 49, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 49 },
    { "vcf_env_polarity", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 50, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 50 },
    { "vcf_pole_mode", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 51, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 51 },
    { "hpf_boost_enable", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 52, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 52 },
    { "env1_attack", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 53, WireCodec::Value, 255, "s", 0.0f, 10.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Log, 53 },
    { "env1_decay", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 54, WireCodec::Value, 255, "s", 0.0f, 10.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Log, 54 },
    { "env1_sustain", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 55, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 55 },
    { "env1_release", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 56, WireCodec::Value, 255, "s", 0.0f, 10.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Log, 56 },
    { "env1_trigger_mode", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 57, WireCodec::Enum, 4, "index", 0.0f, 4.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 57 },
    { "env1_attack_curve", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 58, WireCodec::Value, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 58 },
    { "env1_decay_curve", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 59, WireCodec::Value, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 59 },
    { "env1_sustain_curve", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 60, WireCodec::Value, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 60 },
    { "env1_release_curve", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 61, WireCodec::Value, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 61 },
    { "env2_attack", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 62, WireCodec::Value, 255, "s", 0.0f, 10.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Log, 62 },
    { "env2_decay", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 63, WireCodec::Value, 255, "s", 0.0f, 10.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Log, 63 },
    { "env2_sustain", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 64, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 64 },
    { "env2_release", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 65, WireCodec::Value, 255, "s", 0.0f, 10.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Log, 65 },
    { "env2_trigger_mode", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 66, WireCodec::Enum, 4, "index", 0.0f, 4.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 66 },
    { "env2_attack_curve", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 67, WireCodec::Value, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 67 },
    { "env2_decay_curve", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 68, WireCodec::Value, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 68 },
    { "env2_sustain_curve", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 69, WireCodec::Value, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 69 },
    { "env2_release_curve", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 70, WireCodec::Value, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 70 },
    { "env3_attack", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 71, WireCodec::Value, 255, "s", 0.0f, 10.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Log, 71 },
    { "env3_decay", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 72, WireCodec::Value, 255, "s", 0.0f, 10.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Log, 72 },
    { "env3_sustain", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 73, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 73 },
    { "env3_release", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 74, WireCodec::Value, 255, "s", 0.0f, 10.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Log, 74 },
    { "env3_trigger_mode", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 75, WireCodec::Enum, 4, "index", 0.0f, 4.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 75 },
    { "env3_attack_curve", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 76, WireCodec::Value, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 76 },
    { "env3_decay_curve", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 77, WireCodec::Value, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 77 },
    { "env3_sustain_curve", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 78, WireCodec::Value, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 78 },
    { "env3_release_curve", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 79, WireCodec::Value, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 79 },
    { "vca_level", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 80, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 80 },
    { "vca_env_depth", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 81, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 81 },
    { "vca_vel_sens", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 82, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 82 },
    { "vca_pan_spread", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 83, WireCodec::Bipolar, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 83 },
    { "note_priority", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 84, WireCodec::Enum, 2, "index", 0.0f, 2.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 84 },
    { "voice_mode", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 85, WireCodec::Enum, 12, "index", 0.0f, 12.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 85 },
    { "trigger_mode", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 86, WireCodec::Enum, 3, "index", 0.0f, 3.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 86 },
    { "unison_detune", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 87, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 87 },
    { "voice_drift", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 88, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 88 },
    { "param_drift", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 89, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 89 },
    { "drift_rate", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 90, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 90 },
    { "porta_osc_bal", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 91, WireCodec::Bipolar, 255, "bipolar", -128.0f, 127.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 91 },
    { "osc_key_reset", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 92, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 92 },
    { "mod_matrix_slot1_src", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 93, WireCodec::Enum, 22, "index", 0.0f, 22.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 93 },
    { "mod_matrix_slot1_dest", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 94, WireCodec::Enum, 129, "index", 0.0f, 129.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 94 },
    { "mod_matrix_slot1_depth", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 95, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 95 },
    { "mod_matrix_slot2_src", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 96, WireCodec::Enum, 22, "index", 0.0f, 22.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 96 },
    { "mod_matrix_slot2_dest", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 97, WireCodec::Enum, 129, "index", 0.0f, 129.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 97 },
    { "mod_matrix_slot2_depth", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 98, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 98 },
    { "mod_matrix_slot3_src", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 99, WireCodec::Enum, 22, "index", 0.0f, 22.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 99 },
    { "mod_matrix_slot3_dest", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 100, WireCodec::Enum, 129, "index", 0.0f, 129.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 100 },
    { "mod_matrix_slot3_depth", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 101, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 101 },
    { "mod_matrix_slot4_src", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 102, WireCodec::Enum, 22, "index", 0.0f, 22.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 102 },
    { "mod_matrix_slot4_dest", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 103, WireCodec::Enum, 129, "index", 0.0f, 129.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 103 },
    { "mod_matrix_slot4_depth", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 104, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 104 },
    { "mod_matrix_slot5_src", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 105, WireCodec::Enum, 22, "index", 0.0f, 22.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 105 },
    { "mod_matrix_slot5_dest", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 106, WireCodec::Enum, 129, "index", 0.0f, 129.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 106 },
    { "mod_matrix_slot5_depth", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 107, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 107 },
    { "mod_matrix_slot6_src", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 108, WireCodec::Enum, 22, "index", 0.0f, 22.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 108 },
    { "mod_matrix_slot6_dest", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 109, WireCodec::Enum, 129, "index", 0.0f, 129.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 109 },
    { "mod_matrix_slot6_depth", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 110, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 110 },
    { "mod_matrix_slot7_src", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 111, WireCodec::Enum, 22, "index", 0.0f, 22.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 111 },
    { "mod_matrix_slot7_dest", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 112, WireCodec::Enum, 129, "index", 0.0f, 129.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 112 },
    { "mod_matrix_slot7_depth", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 113, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 113 },
    { "mod_matrix_slot8_src", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 114, WireCodec::Enum, 22, "index", 0.0f, 22.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 114 },
    { "mod_matrix_slot8_dest", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 115, WireCodec::Enum, 129, "index", 0.0f, 129.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 115 },
    { "mod_matrix_slot8_depth", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 116, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 116 },
    { "seq_enable", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 117, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 117 },
    { "seq_clock", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 118, WireCodec::Enum, 15, "index", 0.0f, 15.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 118 },
    { "seq_length", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 119, WireCodec::Enum, 31, "index", 0.0f, 31.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 119 },
    { "seq_swing", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 120, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 120 },
    { "seq_key_loop", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 121, WireCodec::Enum, 2, "index", 0.0f, 2.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 121 },
    { "seq_slew_rate", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 122, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 122 },
    { "seq_step_1", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 123, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 123 },
    { "seq_step_2", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 124, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 124 },
    { "seq_step_3", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 125, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 125 },
    { "seq_step_4", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 126, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 126 },
    { "seq_step_5", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 127, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 127 },
    { "seq_step_6", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 128, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 128 },
    { "seq_step_7", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 129, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 129 },
    { "seq_step_8", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 130, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 130 },
    { "seq_step_9", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 131, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 131 },
    { "seq_step_10", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 132, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 132 },
    { "seq_step_11", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 133, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 133 },
    { "seq_step_12", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 134, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 134 },
    { "seq_step_13", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 135, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 135 },
    { "seq_step_14", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 136, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 136 },
    { "seq_step_15", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 137, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 137 },
    { "seq_step_16", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 138, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 138 },
    { "seq_step_17", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 139, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 139 },
    { "seq_step_18", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 140, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 140 },
    { "seq_step_19", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 141, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 141 },
    { "seq_step_20", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 142, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 142 },
    { "seq_step_21", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 143, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 143 },
    { "seq_step_22", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 144, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 144 },
    { "seq_step_23", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 145, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 145 },
    { "seq_step_24", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 146, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 146 },
    { "seq_step_25", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 147, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 147 },
    { "seq_step_26", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 148, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 148 },
    { "seq_step_27", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 149, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 149 },
    { "seq_step_28", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 150, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 150 },
    { "seq_step_29", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 151, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 151 },
    { "seq_step_30", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 152, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 152 },
    { "seq_step_31", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 153, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 153 },
    { "seq_step_32", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 154, WireCodec::Bipolar, 255, "bipolar", -1.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 154 },
    { "arp_enable", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 155, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 155 },
    { "poly_chord_enable", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 156 },
    { "chord_enable", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 157 },
    { "chord_type", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Enum, 7, "index", 0.0f, 7.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 158 },
    { "arp_mode", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 156, WireCodec::Enum, 10, "index", 0.0f, 10.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 159 },
    { "arp_rate", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 157, WireCodec::Value, 255, "BPM", 20.0f, 275.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 160 },
    { "arp_clock_divider", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 158, WireCodec::Enum, 12, "index", 0.0f, 12.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 161 },
    { "arp_key_sync", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 159, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 162 },
    { "arp_gate_time", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 160, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 163 },
    { "arp_hold", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 161, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 164 },
    { "arp_pattern", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 162, WireCodec::Enum, 64, "index", 0.0f, 64.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 165 },
    { "arp_swing", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 163, WireCodec::Value, 255, "ratio", 0.0f, 25.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 166 },
    { "arp_octave", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 164, WireCodec::Enum, 3, "index", 0.0f, 3.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 167 },
    { "fx_routing", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 165, WireCodec::Enum, 9, "index", 0.0f, 9.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 168 },
    { "fx1_type", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 166, WireCodec::Enum, 49, "index", 0.0f, 49.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 169 },
    { "fx1_param1", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 167, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 170 },
    { "fx1_param2", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 168, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 171 },
    { "fx1_param3", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 169, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 172 },
    { "fx1_param4", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 170, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 173 },
    { "fx1_param5", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 171, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 174 },
    { "fx1_param6", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 172, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 175 },
    { "fx1_param7", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 173, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 176 },
    { "fx1_param8", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 174, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 177 },
    { "fx1_param9", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 175, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 178 },
    { "fx1_param10", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 176, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 179 },
    { "fx1_param11", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 177, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 180 },
    { "fx1_param12", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 178, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 181 },
    { "fx2_type", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 179, WireCodec::Enum, 49, "index", 0.0f, 49.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 182 },
    { "fx2_param1", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 180, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 183 },
    { "fx2_param2", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 181, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 184 },
    { "fx2_param3", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 182, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 185 },
    { "fx2_param4", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 183, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 186 },
    { "fx2_param5", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 184, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 187 },
    { "fx2_param6", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 185, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 188 },
    { "fx2_param7", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 186, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 189 },
    { "fx2_param8", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 187, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 190 },
    { "fx2_param9", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 188, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 191 },
    { "fx2_param10", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 189, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 192 },
    { "fx2_param11", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 190, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 193 },
    { "fx2_param12", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 191, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 194 },
    { "fx3_type", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 192, WireCodec::Enum, 49, "index", 0.0f, 49.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 195 },
    { "fx3_param1", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 193, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 196 },
    { "fx3_param2", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 194, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 197 },
    { "fx3_param3", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 195, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 198 },
    { "fx3_param4", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 196, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 199 },
    { "fx3_param5", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 197, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 200 },
    { "fx3_param6", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 198, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 201 },
    { "fx3_param7", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 199, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 202 },
    { "fx3_param8", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 200, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 203 },
    { "fx3_param9", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 201, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 204 },
    { "fx3_param10", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 202, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 205 },
    { "fx3_param11", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 203, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 206 },
    { "fx3_param12", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 204, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 207 },
    { "fx4_type", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 205, WireCodec::Enum, 49, "index", 0.0f, 49.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 208 },
    { "fx4_param1", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 206, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 209 },
    { "fx4_param2", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 207, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 210 },
    { "fx4_param3", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 208, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 211 },
    { "fx4_param4", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 209, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 212 },
    { "fx4_param5", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 210, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 213 },
    { "fx4_param6", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 211, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 214 },
    { "fx4_param7", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 212, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 215 },
    { "fx4_param8", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 213, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 216 },
    { "fx4_param9", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 214, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 217 },
    { "fx4_param10", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 215, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 218 },
    { "fx4_param11", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 216, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 219 },
    { "fx4_param12", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 217, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 220 },
    { "fx1_gain", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 218, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 221 },
    { "fx2_gain", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 219, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 222 },
    { "fx3_gain", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 220, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 223 },
    { "fx4_gain", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 221, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 224 },
    { "fx_mode", Model::Dm12Hardware, 1, Regime::Fidelity, Wire::SysEx, 222, WireCodec::Enum, 2, "index", 0.0f, 2.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 225 },
    { "fx_feedback_gain", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 226 },
    { "fx_send_level", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 227 },
    { "vcf_model", Model::AbyssmindPro, 2, Regime::Free, Wire::SysEx, 245, WireCodec::Enum, 2, "index", 0.0f, 2.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 228 },
    { "vcf_moog_submode", Model::AbyssmindPro, 2, Regime::Free, Wire::SysEx, 246, WireCodec::Enum, 2, "index", 0.0f, 2.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 229 },
    { "vcf_korg_submode", Model::AbyssmindPro, 2, Regime::Free, Wire::SysEx, 247, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 230 },
    { "vcf_voicing_mode", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, 231 },
    { "arp_velocity_gate", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Enum, 2, "index", 0.0f, 2.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, kNoRegistryIndex },
    { "fx1_mix", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, kNoRegistryIndex },
    { "fx2_mix", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, kNoRegistryIndex },
    { "fx3_mix", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, kNoRegistryIndex },
    { "fx4_mix", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, kNoRegistryIndex },
    { "global_tune", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Value, 255, "cent", -128.0f, 127.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, kNoRegistryIndex },
    { "global_volume", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Value, 255, "ratio", 0.0f, 2.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, kNoRegistryIndex },
    { "hpf_bass_boost_gain", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Value, 255, "ratio", 0.1f, 3.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, kNoRegistryIndex },
    { "master_softclip_bypass", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, kNoRegistryIndex },
    { "master_softclip_headroom", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Value, 255, "dB", 0.0f, 6.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, kNoRegistryIndex },
    { "sub_level", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Value, 255, "ratio", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, kNoRegistryIndex },
    { "transpose", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Value, 255, "semitone", -48.0f, 48.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, kNoRegistryIndex },
    { "vca_mode", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Enum, 1, "index", 0.0f, 1.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, kNoRegistryIndex },
    { "vcf_oversample", Model::AbyssmindPro, 2, Regime::Free, Wire::None, kWireOffsetNone, WireCodec::Enum, 2, "index", 0.0f, 2.0f, Curve::Linear, 0.000000f, 0.000000f, nullptr, 0, nullptr, 0, Smoothing::Linear, kNoRegistryIndex },
}};

const Entry* findConversionById (std::string_view id) noexcept
{
    for (const auto& e : kConversions)
        if (id == e.id)
            return &e;
    return nullptr;
}

float normalizedToDomain (const Entry& e, float t) noexcept
{
    t = clamp01 (t);
    switch (e.curve)
    {
        case Curve::Exp: return e.curveP0 * std::exp (e.curveP1 * t);
        case Curve::Pow: return lerp (e.domainMin, e.domainMax, std::pow (t, e.curveP0));
        case Curve::Lut:
        {
            if (e.lut == nullptr || e.lutSize < 2) return lerp (e.domainMin, e.domainMax, t);
            const float pos = t * static_cast<float> (e.lutSize - 1);
            const auto i = static_cast<std::uint16_t> (pos);
            if (i >= e.lutSize - 1) return e.lut[e.lutSize - 1];
            return lerp (e.lut[i], e.lut[i + 1], pos - static_cast<float> (i));
        }
        default: return lerp (e.domainMin, e.domainMax, t);
    }
}

float domainToNormalized (const Entry& e, float d) noexcept
{
    const float span = e.domainMax - e.domainMin;
    switch (e.curve)
    {
        case Curve::Exp: return e.curveP0 > 0.0f ? clamp01 (std::log (d / e.curveP0) / e.curveP1) : 0.0f;
        case Curve::Pow: return span != 0.0f ? clamp01 (std::pow ((d - e.domainMin) / span, 1.0f / e.curveP0)) : 0.0f;
        case Curve::Lut:
        {
            if (e.lut == nullptr || e.lutSize < 2) return span != 0.0f ? clamp01 ((d - e.domainMin) / span) : 0.0f;
            for (std::uint16_t i = 0; i + 1 < e.lutSize; ++i)
            {
                const float a = e.lut[i], b = e.lut[i + 1];
                if (d >= a && d <= b && b != a)
                    return clamp01 ((static_cast<float> (i) + (d - a) / (b - a)) / static_cast<float> (e.lutSize - 1));
            }
            return d <= e.lut[0] ? 0.0f : 1.0f;
        }
        default: return span != 0.0f ? clamp01 ((d - e.domainMin) / span) : 0.0f;
    }
}

float wireToDomain (const Entry& e, std::uint16_t raw) noexcept
{
    const std::uint16_t r = raw <= e.wireMax ? raw : e.wireMax;
    if (e.wireCodec == WireCodec::Enum)
    {
        const std::uint16_t idx = (e.enumOrder != nullptr && r < e.enumOrderSize) ? e.enumOrder[r] : r;
        return static_cast<float> (idx);
    }
    float t;
    if (e.wireCodec == WireCodec::Bipolar)
        t = (r < kBipolarCenter)
              ? (static_cast<float> (r) / static_cast<float> (kBipolarLowSpan)) * 0.5f
              : 0.5f + (static_cast<float> (r - kBipolarCenter) / static_cast<float> (kBipolarHighSpan)) * 0.5f;
    else
        t = e.wireMax != 0 ? static_cast<float> (r) / static_cast<float> (e.wireMax) : 0.0f;
    return normalizedToDomain (e, t);
}

std::uint16_t domainToWire (const Entry& e, float domain) noexcept
{
    if (e.wireCodec == WireCodec::Enum)
    {
        const int idx = static_cast<int> (std::lround (domain));
        const auto clamped = static_cast<std::uint16_t> (idx < 0 ? 0 : (idx > static_cast<int> (e.wireMax) ? e.wireMax : idx));
        if (e.enumOrder != nullptr)
            for (std::uint16_t i = 0; i < e.enumOrderSize; ++i)
                if (e.enumOrder[i] == clamped)
                    return i;
        return clamped;
    }
    const float t = domainToNormalized (e, domain);
    const float raw = (e.wireCodec == WireCodec::Bipolar)
                        ? ((t <= 0.5f) ? t * 2.0f * static_cast<float> (kBipolarLowSpan)
                                        : static_cast<float> (kBipolarCenter) + (t - 0.5f) * 2.0f * static_cast<float> (kBipolarHighSpan))
                        : t * static_cast<float> (e.wireMax);
    const long r = std::lround (raw);
    return static_cast<std::uint16_t> (r < 0 ? 0 : (r > static_cast<long> (e.wireMax) ? e.wireMax : r));
}

} // namespace Conversion
} // namespace Registry
} // namespace ABD
