// AUTO-GENERATED by scripts/validate_and_generate.ps1 → registry_generator.js — DO NOT EDIT.
//
// Capa de traduccion wire <-> dominio. Cubre los 246 parametros del APVTS.
// Clave de entrada: (model, protocolVersion, parameterId).
// Ver schemas/parameter-conversion.json (fuente de verdad) y su cabecera.
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace ABD
{
namespace Registry
{
namespace Conversion
{

enum class Model : std::uint8_t
{
    Dm12Hardware = 0,
    AbyssmindPro = 1,
};

enum class Regime : std::uint8_t { Fidelity = 0, Free = 1 };
enum class Wire : std::uint8_t { None = 0, SysEx = 1, Nrpn = 2 };
enum class WireCodec : std::uint8_t { Value = 0, Bipolar = 1, Enum = 2 };
enum class Curve : std::uint8_t { Linear = 0, Exp = 1, Pow = 2, Lut = 3 };
enum class Smoothing : std::uint8_t { Linear = 0, Log = 1 };

/** No hay wire que leer: el parametro no viene de ningun byte. */
inline constexpr std::uint16_t kWireOffsetNone = 0xFFFF;
/** El parametro no esta en el registro (los sin byte del APVTS). */
inline constexpr std::uint16_t kNoRegistryIndex = 0xFFFF;

/**
 * Reglas del wire bipolar, SIMETRICAS en dominio (correccion del defecto 5:
 * el registro usa ((raw-128)/127+1)/2, que no llega a 0 en raw=0 antes del clamp).
 *   raw <  128 -> (raw / kBipolarLowSpan)  * 0.5
 *   raw >= 128 -> 0.5 + ((raw-128) / kBipolarHighSpan) * 0.5
 * Centro 128 -> 0.5 exacto; 0 y 255 -> 0 y 1.
 */
inline constexpr std::uint16_t kBipolarCenter   = 128;
inline constexpr std::uint16_t kBipolarLowSpan  = 128;
inline constexpr std::uint16_t kBipolarHighSpan = 127;

struct Entry
{
    const char* id;
    Model model;
    std::uint8_t protocolVersion;
    Regime regime;
    Wire wire;
    std::uint16_t wireOffset;        // kWireOffsetNone si wire == None
    WireCodec wireCodec;
    std::uint16_t wireMax;           // 255 (value/bipolar) o el tope del enum
    const char* unit;
    float domainMin;
    float domainMax;
    Curve curve;
    float curveP0;                   // exp: escala; pow: exponente
    float curveP1;                   // exp: exponente
    const float* lut;                // curve Lut: tabla, o nullptr
    std::uint16_t lutSize;
    const std::uint16_t* enumOrder;  // nullptr = identidad
    std::uint16_t enumOrderSize;
    Smoothing smoothingSpace;
    std::uint16_t registryIndex;     // ParameterIndex, o kNoRegistryIndex
};

inline constexpr std::size_t kConversionCount = 246;
inline constexpr std::uint8_t kConversionSchemaVersion = 1;
inline constexpr std::uint16_t kConversionVersion = 2;

extern const std::array<Entry, kConversionCount> kConversions;

// Lookup por id (hilo de control; nunca en el hilo de audio).
const Entry* findConversionById (std::string_view id) noexcept;

// normalized 0..1 <-> dominio, segun la curva del parametro.
float normalizedToDomain (const Entry& entry, float t) noexcept;
float domainToNormalized (const Entry& entry, float domain) noexcept;
// wire <-> dominio: EL CODEC. Es lo que sustituye a los numeros magicos del motor.
float wireToDomain (const Entry& entry, std::uint16_t raw) noexcept;
std::uint16_t domainToWire (const Entry& entry, float domain) noexcept;

} // namespace Conversion
} // namespace Registry
} // namespace ABD
