# ============================================================================
# ABDEep - Listas compartidas de fuentes (single-source, anti-drift)
#
# Consumidas por DOS builds:
#   - CMakeLists.txt raiz (plugin nativo ABDEep_Standalone / VST3)
#   - wasm/CMakeLists.txt (motor WebAssembly, modulos JUCE via juce_shim)
#
# HISTORIA: dos listas a mano derivaron 57 ficheros. Tras la auditoria, la
# diferencia es mayoritariamente principista (herramientas nativas); el unico
# modulo del motor web que faltaba era BankFileReader (ya recuperado).
#
# ABDEEP_DSP_SOURCES      : DSP + Core + Calibration (comunes nativo/web).
# ABDEEP_DSP_SOURCES_WASM : subconjunto headless para Emscripten. Exclusiones
#                           documentadas (NO drift):
#   - Plugin/*  (processor/editor/bridges): frontend nativo.
#   - Tools/*   (CalibrationLab, benchmarks, suites de tests): nativas.
#   - Core/ParametersSpec* + RoundTripValidator: layout APVTS del plugin
#     nativo (RoundTripValidator incluye ParametersSpec.h); la variante
#     headless de JUCE 8 no es compatible con audio_basics activo
#     (redefiniciones) y el bridge web consume el registry directamente.
#     CalibrationSpec.cpp/_Serialization SI son elegibles (String/File/Array
#     y ValueTree de juce_data_structures, vendado en el WASM).
#   - DSP/FX/FXUnitTests*: suites nativas.
#   - Calibration/*: comparador A/B con captura de audio del sistema.
# Regla: si anades un modulo DSP al nativo, debe ir tambien en WASM (o
# justificarlo en este bloque).
#
# NOTA: CMAKE_CURRENT_LIST_DIR apunta al directorio que contiene este fichero
# (la raiz del proyecto), sea quien sea el consumidor.
# ============================================================================

set(ABDEEP_DSP_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/Source/Calibration/AudioABComparator.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/Calibration/AudioABComparator_Alignment.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/Calibration/AudioABComparator_Spectral.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/Calibration/AudioABRecorder.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/Calibration/AudioABRecorder_Process.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/Calibration/AudioABVerdictEngine.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/Core/BankFileReader.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/Core/ParameterRegistry.gen.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/DriftEngine.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/Envelope.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXAnalogTapeDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXAutoPan.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXBonsai.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXChorus.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXChorusD.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXCombulator.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXDecimDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXDuckingDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXEdison.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXEngine.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXEngine_Routing.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXEnhancer.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXFDNReverb.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXFairComp.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXFlanger.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXFrequencyShifter.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXGranularDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXHybridReverb.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXMidasEQ.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXModDelayRev.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXMoodFilter.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXMultiBandDist.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXMultiTapDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXNimbus.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXNoiseGate.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXOversamplingDistortion.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXPatternFreeze.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXPhaser.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXPitchShifter.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXRackAmp.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXResonator.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXRingModulator.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXRolandBBDChorus.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXRotarySpeaker.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXShimmerDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSimpleComp.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSimpleReverb.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSimpleReverb_Process.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSlot.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSlot_Factory.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSolinaEnsemble.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSpaceEchoRE201.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSpectralDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXTapeDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXTreemonster.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXVocoder.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXVocoder_Filter.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXVocoder_Process.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXWaveShaper.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXZitaReverb.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/Filter.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/JunoVCF_ZDF.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/JunoVCF_ZDF_Process.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/KorgMS20VCF.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/LFO.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/ModulationMatrix.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/MoogLadderVCF.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/OSC1.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/OSC2.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthEngine.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthEngine_MIDI.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthEngine_Parameters.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthEngine_Snapshot.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthEngine_VoiceManager.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthVoice.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthVoice_Diagnostics.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthVoice_Filter.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthVoice_Lifecycle.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthVoice_Pitch.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthVoice_Process.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthVoice_VCA.cpp"
)

set(ABDEEP_DSP_SOURCES_WASM
    "${CMAKE_CURRENT_LIST_DIR}/Source/Core/BankFileReader.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/Core/CalibrationSpec.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/Core/CalibrationSpec_Serialization.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/Core/ParameterRegistry.gen.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/DriftEngine.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/Envelope.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXAnalogTapeDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXAutoPan.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXBonsai.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXChorus.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXChorusD.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXCombulator.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXDecimDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXDuckingDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXEdison.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXEngine.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXEngine_Routing.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXEnhancer.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXFDNReverb.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXFairComp.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXFlanger.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXFrequencyShifter.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXGranularDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXHybridReverb.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXMidasEQ.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXModDelayRev.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXMoodFilter.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXMultiBandDist.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXMultiTapDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXNimbus.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXNoiseGate.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXOversamplingDistortion.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXPatternFreeze.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXPhaser.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXPitchShifter.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXRackAmp.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXResonator.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXRingModulator.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXRolandBBDChorus.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXRotarySpeaker.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXShimmerDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSimpleComp.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSimpleReverb.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSimpleReverb_Process.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSlot.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSlot_Factory.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSolinaEnsemble.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSpaceEchoRE201.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXSpectralDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXTapeDelay.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXTreemonster.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXVocoder.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXVocoder_Filter.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXVocoder_Process.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXWaveShaper.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/FX/FXZitaReverb.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/Filter.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/JunoVCF_ZDF.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/JunoVCF_ZDF_Process.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/KorgMS20VCF.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/LFO.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/ModulationMatrix.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/MoogLadderVCF.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/OSC1.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/OSC2.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthEngine.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthEngine_MIDI.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthEngine_Parameters.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthEngine_Snapshot.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthEngine_VoiceManager.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthVoice.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthVoice_Diagnostics.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthVoice_Filter.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthVoice_Lifecycle.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthVoice_Pitch.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthVoice_Process.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/DSP/SynthVoice_VCA.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Source/Wasm/WasmBridge.cpp"
)
