/**
 * @purpose Loader for categorized factory FX presets.
 * ⚠️ GENERATED FILE — Do not edit manually.
 * Generated by scripts/build-fx-presets.js
 */

window.FACTORY_FX_PRESETS = Object.assign(
    [],
    window.FX_PRESETS_REVERBS || [],
    window.FX_PRESETS_DELAYS || [],
    window.FX_PRESETS_MODULATION || [],
    window.FX_PRESETS_ADVANCED || []
);
