/* AUTO-GENERATED by scripts/generate_fx_contract.mjs from ABDSharedAssets/contracts/fx-effects.json — DO NOT EDIT. */
/* eslint-disable */
(function (root, factory) {
  // SE ASIGNA A LOS TRES NOMBRES, Y NO ES "UNA VERDAD TRES VECES".
  //
  // Antes era un if/else: con `module` presente (cualquier bundler, y tambien
  // vitest) se escribia solo `module.exports` y `window.FxEffectsContract`
  // NO LLEGABA A PONERSE. Todo el que consume el contrato en la WebUI lee
  // `window.FxEffectsContract`, asi que empaquetado el rack de efectos se
  // quedaba sin un solo efecto, sin error y sin aviso: el desplegable vacio y
  // los doce mandos de cada hueco apagados.
  //
  // Aqui sale un solo objeto y se publica por los tres sitios que usan los
  // distintos cargadores. Es el MISMO objeto, no tres verdades: lo unico que
  // cambia es el nombre por el que se puede alcanzar.
  var contrato = factory();

  if (typeof module === "object" && module && module.exports) { module.exports = contrato; }
  if (typeof window !== "undefined") { window.FxEffectsContract = contrato; }
  if (root) { root.FxEffectsContract = contrato; }

  return contrato;
})(typeof self !== "undefined" ? self : globalThis, function () {
  return {
  "title": "Catalogo de efectos del rack FX compartido",
  "source": "ABDSharedAssets/contracts/fx-effects.json",
  "sourceHash": "988630b283149697a271251926a258be5f8cf728e6303d09dd1fda0bc40265e5",
  "count": 61,
  "maxId": 60,
  "families": {
    "bypass": 1,
    "reverb": 17,
    "delay": 4,
    "tape": 7,
    "chorus": 4,
    "modulation": 4,
    "filter": 5,
    "dynamics": 2,
    "distortion": 6,
    "pitch": 4,
    "space": 7
  },
  "names": [
    "Bypass",
    "Hall",
    "Plate",
    "Rich Plate",
    "Ambience",
    "Gated",
    "Reverse",
    "Rack Amp",
    "Mood Filter",
    "Stereo Phaser",
    "Stereo Chorus",
    "Stereo Flanger",
    "Mod Delay Verb",
    "Delay",
    "3-Tap Delay",
    "4-Tap Delay",
    "Rotary Speaker",
    "Chorus-D",
    "Enhancer",
    "Edison EX1",
    "Auto Pan",
    "T-Ray Delay",
    "Deep Verb",
    "Flang Verb",
    "Chorus Verb",
    "Delay Verb",
    "Chamber",
    "Room",
    "Vintage",
    "Dual Pitch",
    "Midas EQ",
    "Fair Comp",
    "Multi-Band Dist",
    "Noise Gate",
    "Decimator Delay",
    "Vintage Pitch",
    "BBD Chorus",
    "Solina Ensemble",
    "Ring Mod",
    "Space Echo",
    "Analog Tape Delay",
    "Shimmer Delay",
    "Granular Delay",
    "Pattern Freeze",
    "Ducking Delay",
    "Spectral Delay",
    "Frequency Shifter",
    "Harmonic Reso",
    "Combulator",
    "MB Vocoder",
    "Oversampled Dist",
    "Wave Shaper",
    "FDN Reverb",
    "Zita Reverb",
    "Nimbus",
    "Bonsai",
    "Tree Monster",
    "FreeVerb Reverb",
    "Saturation",
    "Schroeder Reverb",
    "Shelf Filter"
  ],
  "effects": [
    {
      "id": 0,
      "name": "Bypass",
      "engine": null,
      "variant": null,
      "family": "bypass",
      "params": 0
    },
    {
      "id": 1,
      "name": "Hall",
      "engine": "SimpleReverb",
      "variant": 1,
      "family": "reverb",
      "params": 12
    },
    {
      "id": 2,
      "name": "Plate",
      "engine": "SimpleReverb",
      "variant": 2,
      "family": "reverb",
      "params": 12
    },
    {
      "id": 3,
      "name": "Rich Plate",
      "engine": "SimpleReverb",
      "variant": 3,
      "family": "reverb",
      "params": 12
    },
    {
      "id": 4,
      "name": "Ambience",
      "engine": "SimpleReverb",
      "variant": 4,
      "family": "reverb",
      "params": 10
    },
    {
      "id": 5,
      "name": "Gated",
      "engine": "SimpleReverb",
      "variant": 5,
      "family": "reverb",
      "params": 10
    },
    {
      "id": 6,
      "name": "Reverse",
      "engine": "SimpleReverb",
      "variant": 6,
      "family": "reverb",
      "params": 9
    },
    {
      "id": 22,
      "name": "Deep Verb",
      "engine": "SimpleReverb",
      "variant": 22,
      "family": "reverb",
      "params": 5
    },
    {
      "id": 26,
      "name": "Chamber",
      "engine": "SimpleReverb",
      "variant": 26,
      "family": "reverb",
      "params": 12
    },
    {
      "id": 27,
      "name": "Room",
      "engine": "SimpleReverb",
      "variant": 27,
      "family": "reverb",
      "params": 12
    },
    {
      "id": 28,
      "name": "Vintage",
      "engine": "SimpleReverb",
      "variant": 28,
      "family": "reverb",
      "params": 12
    },
    {
      "id": 23,
      "name": "Flang Verb",
      "engine": "HybridReverb",
      "variant": 23,
      "family": "reverb",
      "params": 12
    },
    {
      "id": 24,
      "name": "Chorus Verb",
      "engine": "HybridReverb",
      "variant": 24,
      "family": "reverb",
      "params": 12
    },
    {
      "id": 25,
      "name": "Delay Verb",
      "engine": "HybridReverb",
      "variant": 25,
      "family": "reverb",
      "params": 12
    },
    {
      "id": 52,
      "name": "FDN Reverb",
      "engine": "FDNReverb",
      "variant": null,
      "family": "reverb",
      "params": 5
    },
    {
      "id": 53,
      "name": "Zita Reverb",
      "engine": "ZitaReverb",
      "variant": null,
      "family": "reverb",
      "params": 5
    },
    {
      "id": 13,
      "name": "Delay",
      "engine": "Delay",
      "variant": null,
      "family": "delay",
      "params": 12
    },
    {
      "id": 14,
      "name": "3-Tap Delay",
      "engine": "MultiTapDelay",
      "variant": 3,
      "family": "delay",
      "params": 12
    },
    {
      "id": 15,
      "name": "4-Tap Delay",
      "engine": "MultiTapDelay",
      "variant": 4,
      "family": "delay",
      "params": 12
    },
    {
      "id": 12,
      "name": "Mod Delay Verb",
      "engine": "ModDelayRev",
      "variant": null,
      "family": "delay",
      "params": 12
    },
    {
      "id": 21,
      "name": "T-Ray Delay",
      "engine": "TapeDelay",
      "variant": null,
      "family": "tape",
      "params": 5
    },
    {
      "id": 34,
      "name": "Decimator Delay",
      "engine": "DecimDelay",
      "variant": null,
      "family": "tape",
      "params": 12
    },
    {
      "id": 40,
      "name": "Analog Tape Delay",
      "engine": "AnalogTapeDelay",
      "variant": null,
      "family": "tape",
      "params": 6
    },
    {
      "id": 41,
      "name": "Shimmer Delay",
      "engine": "ShimmerDelay",
      "variant": null,
      "family": "tape",
      "params": 5
    },
    {
      "id": 42,
      "name": "Granular Delay",
      "engine": "GranularDelay",
      "variant": null,
      "family": "tape",
      "params": 5
    },
    {
      "id": 44,
      "name": "Ducking Delay",
      "engine": "DuckingDelay",
      "variant": null,
      "family": "tape",
      "params": 5
    },
    {
      "id": 45,
      "name": "Spectral Delay",
      "engine": "SpectralDelay",
      "variant": null,
      "family": "tape",
      "params": 5
    },
    {
      "id": 10,
      "name": "Stereo Chorus",
      "engine": "Chorus",
      "variant": null,
      "family": "chorus",
      "params": 11
    },
    {
      "id": 17,
      "name": "Chorus-D",
      "engine": "ChorusD",
      "variant": null,
      "family": "chorus",
      "params": 7
    },
    {
      "id": 36,
      "name": "BBD Chorus",
      "engine": "RolandBBDChorus",
      "variant": null,
      "family": "chorus",
      "params": 4
    },
    {
      "id": 37,
      "name": "Solina Ensemble",
      "engine": "SolinaEnsemble",
      "variant": null,
      "family": "chorus",
      "params": 5
    },
    {
      "id": 9,
      "name": "Stereo Phaser",
      "engine": "Phaser",
      "variant": null,
      "family": "modulation",
      "params": 12
    },
    {
      "id": 11,
      "name": "Stereo Flanger",
      "engine": "Flanger",
      "variant": null,
      "family": "modulation",
      "params": 12
    },
    {
      "id": 20,
      "name": "Auto Pan",
      "engine": "AutoPan",
      "variant": null,
      "family": "modulation",
      "params": 9
    },
    {
      "id": 38,
      "name": "Ring Mod",
      "engine": "RingModulator",
      "variant": null,
      "family": "modulation",
      "params": 5
    },
    {
      "id": 30,
      "name": "Midas EQ",
      "engine": "MidasEQ",
      "variant": null,
      "family": "filter",
      "params": 11
    },
    {
      "id": 8,
      "name": "Mood Filter",
      "engine": "MoodFilter",
      "variant": null,
      "family": "filter",
      "params": 12
    },
    {
      "id": 47,
      "name": "Harmonic Reso",
      "engine": "Resonator",
      "variant": null,
      "family": "filter",
      "params": 5
    },
    {
      "id": 48,
      "name": "Combulator",
      "engine": "Combulator",
      "variant": null,
      "family": "filter",
      "params": 5
    },
    {
      "id": 31,
      "name": "Fair Comp",
      "engine": "FairComp",
      "variant": null,
      "family": "dynamics",
      "params": 12
    },
    {
      "id": 33,
      "name": "Noise Gate",
      "engine": "NoiseGate",
      "variant": null,
      "family": "dynamics",
      "params": 8
    },
    {
      "id": 32,
      "name": "Multi-Band Dist",
      "engine": "MultiBandDist",
      "variant": null,
      "family": "distortion",
      "params": 12
    },
    {
      "id": 50,
      "name": "Oversampled Dist",
      "engine": "OversamplingDistortion",
      "variant": null,
      "family": "distortion",
      "params": 5
    },
    {
      "id": 51,
      "name": "Wave Shaper",
      "engine": "WaveShaper",
      "variant": null,
      "family": "distortion",
      "params": 5
    },
    {
      "id": 18,
      "name": "Enhancer",
      "engine": "Enhancer",
      "variant": null,
      "family": "distortion",
      "params": 9
    },
    {
      "id": 7,
      "name": "Rack Amp",
      "engine": "RackAmp",
      "variant": null,
      "family": "distortion",
      "params": 9
    },
    {
      "id": 29,
      "name": "Dual Pitch",
      "engine": "PitchShifter",
      "variant": "dual",
      "family": "pitch",
      "params": 12
    },
    {
      "id": 35,
      "name": "Vintage Pitch",
      "engine": "PitchShifter",
      "variant": "vintage",
      "family": "pitch",
      "params": 12
    },
    {
      "id": 46,
      "name": "Frequency Shifter",
      "engine": "FrequencyShifter",
      "variant": null,
      "family": "pitch",
      "params": 5
    },
    {
      "id": 55,
      "name": "Bonsai",
      "engine": "Bonsai",
      "variant": null,
      "family": "pitch",
      "params": 5
    },
    {
      "id": 39,
      "name": "Space Echo",
      "engine": "SpaceEchoRE201",
      "variant": null,
      "family": "space",
      "params": 6
    },
    {
      "id": 16,
      "name": "Rotary Speaker",
      "engine": "RotarySpeaker",
      "variant": null,
      "family": "space",
      "params": 8
    },
    {
      "id": 19,
      "name": "Edison EX1",
      "engine": "Edison",
      "variant": null,
      "family": "space",
      "params": 8
    },
    {
      "id": 43,
      "name": "Pattern Freeze",
      "engine": "PatternFreeze",
      "variant": null,
      "family": "space",
      "params": 4
    },
    {
      "id": 49,
      "name": "MB Vocoder",
      "engine": "Vocoder",
      "variant": null,
      "family": "space",
      "params": 6
    },
    {
      "id": 54,
      "name": "Nimbus",
      "engine": "Nimbus",
      "variant": null,
      "family": "space",
      "params": 5
    },
    {
      "id": 56,
      "name": "Tree Monster",
      "engine": "Treemonster",
      "variant": null,
      "family": "space",
      "params": 5
    },
    {
      "id": 57,
      "name": "FreeVerb Reverb",
      "engine": "Reverb",
      "variant": null,
      "family": "reverb",
      "params": 4
    },
    {
      "id": 58,
      "name": "Saturation",
      "engine": "Saturation",
      "variant": null,
      "family": "distortion",
      "params": 1
    },
    {
      "id": 59,
      "name": "Schroeder Reverb",
      "engine": "SchroederReverb",
      "variant": null,
      "family": "reverb",
      "params": 4
    },
    {
      "id": 60,
      "name": "Shelf Filter",
      "engine": "ShelfFilter",
      "variant": null,
      "family": "filter",
      "params": 3
    }
  ],
  "byId": {
    "0": {
      "id": 0,
      "name": "Bypass",
      "engine": null,
      "variant": null,
      "family": "bypass",
      "params": 0
    },
    "1": {
      "id": 1,
      "name": "Hall",
      "engine": "SimpleReverb",
      "variant": 1,
      "family": "reverb",
      "params": 12
    },
    "2": {
      "id": 2,
      "name": "Plate",
      "engine": "SimpleReverb",
      "variant": 2,
      "family": "reverb",
      "params": 12
    },
    "3": {
      "id": 3,
      "name": "Rich Plate",
      "engine": "SimpleReverb",
      "variant": 3,
      "family": "reverb",
      "params": 12
    },
    "4": {
      "id": 4,
      "name": "Ambience",
      "engine": "SimpleReverb",
      "variant": 4,
      "family": "reverb",
      "params": 10
    },
    "5": {
      "id": 5,
      "name": "Gated",
      "engine": "SimpleReverb",
      "variant": 5,
      "family": "reverb",
      "params": 10
    },
    "6": {
      "id": 6,
      "name": "Reverse",
      "engine": "SimpleReverb",
      "variant": 6,
      "family": "reverb",
      "params": 9
    },
    "7": {
      "id": 7,
      "name": "Rack Amp",
      "engine": "RackAmp",
      "variant": null,
      "family": "distortion",
      "params": 9
    },
    "8": {
      "id": 8,
      "name": "Mood Filter",
      "engine": "MoodFilter",
      "variant": null,
      "family": "filter",
      "params": 12
    },
    "9": {
      "id": 9,
      "name": "Stereo Phaser",
      "engine": "Phaser",
      "variant": null,
      "family": "modulation",
      "params": 12
    },
    "10": {
      "id": 10,
      "name": "Stereo Chorus",
      "engine": "Chorus",
      "variant": null,
      "family": "chorus",
      "params": 11
    },
    "11": {
      "id": 11,
      "name": "Stereo Flanger",
      "engine": "Flanger",
      "variant": null,
      "family": "modulation",
      "params": 12
    },
    "12": {
      "id": 12,
      "name": "Mod Delay Verb",
      "engine": "ModDelayRev",
      "variant": null,
      "family": "delay",
      "params": 12
    },
    "13": {
      "id": 13,
      "name": "Delay",
      "engine": "Delay",
      "variant": null,
      "family": "delay",
      "params": 12
    },
    "14": {
      "id": 14,
      "name": "3-Tap Delay",
      "engine": "MultiTapDelay",
      "variant": 3,
      "family": "delay",
      "params": 12
    },
    "15": {
      "id": 15,
      "name": "4-Tap Delay",
      "engine": "MultiTapDelay",
      "variant": 4,
      "family": "delay",
      "params": 12
    },
    "16": {
      "id": 16,
      "name": "Rotary Speaker",
      "engine": "RotarySpeaker",
      "variant": null,
      "family": "space",
      "params": 8
    },
    "17": {
      "id": 17,
      "name": "Chorus-D",
      "engine": "ChorusD",
      "variant": null,
      "family": "chorus",
      "params": 7
    },
    "18": {
      "id": 18,
      "name": "Enhancer",
      "engine": "Enhancer",
      "variant": null,
      "family": "distortion",
      "params": 9
    },
    "19": {
      "id": 19,
      "name": "Edison EX1",
      "engine": "Edison",
      "variant": null,
      "family": "space",
      "params": 8
    },
    "20": {
      "id": 20,
      "name": "Auto Pan",
      "engine": "AutoPan",
      "variant": null,
      "family": "modulation",
      "params": 9
    },
    "21": {
      "id": 21,
      "name": "T-Ray Delay",
      "engine": "TapeDelay",
      "variant": null,
      "family": "tape",
      "params": 5
    },
    "22": {
      "id": 22,
      "name": "Deep Verb",
      "engine": "SimpleReverb",
      "variant": 22,
      "family": "reverb",
      "params": 5
    },
    "23": {
      "id": 23,
      "name": "Flang Verb",
      "engine": "HybridReverb",
      "variant": 23,
      "family": "reverb",
      "params": 12
    },
    "24": {
      "id": 24,
      "name": "Chorus Verb",
      "engine": "HybridReverb",
      "variant": 24,
      "family": "reverb",
      "params": 12
    },
    "25": {
      "id": 25,
      "name": "Delay Verb",
      "engine": "HybridReverb",
      "variant": 25,
      "family": "reverb",
      "params": 12
    },
    "26": {
      "id": 26,
      "name": "Chamber",
      "engine": "SimpleReverb",
      "variant": 26,
      "family": "reverb",
      "params": 12
    },
    "27": {
      "id": 27,
      "name": "Room",
      "engine": "SimpleReverb",
      "variant": 27,
      "family": "reverb",
      "params": 12
    },
    "28": {
      "id": 28,
      "name": "Vintage",
      "engine": "SimpleReverb",
      "variant": 28,
      "family": "reverb",
      "params": 12
    },
    "29": {
      "id": 29,
      "name": "Dual Pitch",
      "engine": "PitchShifter",
      "variant": "dual",
      "family": "pitch",
      "params": 12
    },
    "30": {
      "id": 30,
      "name": "Midas EQ",
      "engine": "MidasEQ",
      "variant": null,
      "family": "filter",
      "params": 11
    },
    "31": {
      "id": 31,
      "name": "Fair Comp",
      "engine": "FairComp",
      "variant": null,
      "family": "dynamics",
      "params": 12
    },
    "32": {
      "id": 32,
      "name": "Multi-Band Dist",
      "engine": "MultiBandDist",
      "variant": null,
      "family": "distortion",
      "params": 12
    },
    "33": {
      "id": 33,
      "name": "Noise Gate",
      "engine": "NoiseGate",
      "variant": null,
      "family": "dynamics",
      "params": 8
    },
    "34": {
      "id": 34,
      "name": "Decimator Delay",
      "engine": "DecimDelay",
      "variant": null,
      "family": "tape",
      "params": 12
    },
    "35": {
      "id": 35,
      "name": "Vintage Pitch",
      "engine": "PitchShifter",
      "variant": "vintage",
      "family": "pitch",
      "params": 12
    },
    "36": {
      "id": 36,
      "name": "BBD Chorus",
      "engine": "RolandBBDChorus",
      "variant": null,
      "family": "chorus",
      "params": 4
    },
    "37": {
      "id": 37,
      "name": "Solina Ensemble",
      "engine": "SolinaEnsemble",
      "variant": null,
      "family": "chorus",
      "params": 5
    },
    "38": {
      "id": 38,
      "name": "Ring Mod",
      "engine": "RingModulator",
      "variant": null,
      "family": "modulation",
      "params": 5
    },
    "39": {
      "id": 39,
      "name": "Space Echo",
      "engine": "SpaceEchoRE201",
      "variant": null,
      "family": "space",
      "params": 6
    },
    "40": {
      "id": 40,
      "name": "Analog Tape Delay",
      "engine": "AnalogTapeDelay",
      "variant": null,
      "family": "tape",
      "params": 6
    },
    "41": {
      "id": 41,
      "name": "Shimmer Delay",
      "engine": "ShimmerDelay",
      "variant": null,
      "family": "tape",
      "params": 5
    },
    "42": {
      "id": 42,
      "name": "Granular Delay",
      "engine": "GranularDelay",
      "variant": null,
      "family": "tape",
      "params": 5
    },
    "43": {
      "id": 43,
      "name": "Pattern Freeze",
      "engine": "PatternFreeze",
      "variant": null,
      "family": "space",
      "params": 4
    },
    "44": {
      "id": 44,
      "name": "Ducking Delay",
      "engine": "DuckingDelay",
      "variant": null,
      "family": "tape",
      "params": 5
    },
    "45": {
      "id": 45,
      "name": "Spectral Delay",
      "engine": "SpectralDelay",
      "variant": null,
      "family": "tape",
      "params": 5
    },
    "46": {
      "id": 46,
      "name": "Frequency Shifter",
      "engine": "FrequencyShifter",
      "variant": null,
      "family": "pitch",
      "params": 5
    },
    "47": {
      "id": 47,
      "name": "Harmonic Reso",
      "engine": "Resonator",
      "variant": null,
      "family": "filter",
      "params": 5
    },
    "48": {
      "id": 48,
      "name": "Combulator",
      "engine": "Combulator",
      "variant": null,
      "family": "filter",
      "params": 5
    },
    "49": {
      "id": 49,
      "name": "MB Vocoder",
      "engine": "Vocoder",
      "variant": null,
      "family": "space",
      "params": 6
    },
    "50": {
      "id": 50,
      "name": "Oversampled Dist",
      "engine": "OversamplingDistortion",
      "variant": null,
      "family": "distortion",
      "params": 5
    },
    "51": {
      "id": 51,
      "name": "Wave Shaper",
      "engine": "WaveShaper",
      "variant": null,
      "family": "distortion",
      "params": 5
    },
    "52": {
      "id": 52,
      "name": "FDN Reverb",
      "engine": "FDNReverb",
      "variant": null,
      "family": "reverb",
      "params": 5
    },
    "53": {
      "id": 53,
      "name": "Zita Reverb",
      "engine": "ZitaReverb",
      "variant": null,
      "family": "reverb",
      "params": 5
    },
    "54": {
      "id": 54,
      "name": "Nimbus",
      "engine": "Nimbus",
      "variant": null,
      "family": "space",
      "params": 5
    },
    "55": {
      "id": 55,
      "name": "Bonsai",
      "engine": "Bonsai",
      "variant": null,
      "family": "pitch",
      "params": 5
    },
    "56": {
      "id": 56,
      "name": "Tree Monster",
      "engine": "Treemonster",
      "variant": null,
      "family": "space",
      "params": 5
    },
    "57": {
      "id": 57,
      "name": "FreeVerb Reverb",
      "engine": "Reverb",
      "variant": null,
      "family": "reverb",
      "params": 4
    },
    "58": {
      "id": 58,
      "name": "Saturation",
      "engine": "Saturation",
      "variant": null,
      "family": "distortion",
      "params": 1
    },
    "59": {
      "id": 59,
      "name": "Schroeder Reverb",
      "engine": "SchroederReverb",
      "variant": null,
      "family": "reverb",
      "params": 4
    },
    "60": {
      "id": 60,
      "name": "Shelf Filter",
      "engine": "ShelfFilter",
      "variant": null,
      "family": "filter",
      "params": 3
    }
  }
};
});
