/**
 * @purpose Panel templates: Polyphony / Voice Mode (POLY) and Portamento (PORTA).
 *          Appends to window.PANEL_TEMPLATES (initialized by panel_templates.js).
 * @classification UI/Templates
 */

(function () {
    const NS = window.PANEL_TEMPLATES = window.PANEL_TEMPLATES || {};

    NS.POLY = function () { return [
        '<div class="panel-section-title">Polyphony / Voice Mode</div>',
        '<div class="w-full" style="margin-bottom:12px">',
        '    <select id="panel-poly-mode-select" data-param="voice_mode" class="modal-select w-full" style="font-size:9.5px;padding:5px">',
        '        <option value="0">Poly</option>',
        '        <option value="1">Unison 2</option>',
        '        <option value="2">Unison 3</option>',
        '        <option value="3">Unison 4</option>',
        '        <option value="4">Unison 6</option>',
        '        <option value="5">Unison 12</option>',
        '        <option value="6">Mono</option>',
        '        <option value="7">Mono 2</option>',
        '        <option value="8">Mono 3</option>',
        '        <option value="9">Mono 4</option>',
        '        <option value="10">Mono 6</option>',
        '        <option value="11">Poly 6</option>',
        '        <option value="12">Poly 8</option>',
        '    </select>',
        '</div>',
        '',
        '<div class="panel-section-title">Note Priority</div>',
        '<div class="shape-selector-container" style="margin-bottom:12px">',
        '    <div class="shape-led-row priority-led-row" data-val="0" data-param="note_priority"><div class="led-dot"></div><span class="shape-name text-xs">Lowest</span></div>',
        '    <div class="shape-led-row priority-led-row" data-val="1" data-param="note_priority"><div class="led-dot"></div><span class="shape-name text-xs">Highest</span></div>',
        '    <div class="shape-led-row priority-led-row" data-val="2" data-param="note_priority"><div class="led-dot"></div><span class="shape-name text-xs">Last</span></div>',
        '</div>',
        '',
        '<div class="panel-section-title">Envelope Trigger Mode</div>',
        '<div class="shape-selector-container" style="margin-bottom:12px">',
        '    <div class="shape-led-row trigger-led-row" data-val="0" data-param="trigger_mode"><div class="led-dot"></div><span class="shape-name text-xs">Mono</span></div>',
        '    <div class="shape-led-row trigger-led-row" data-val="1" data-param="trigger_mode"><div class="led-dot"></div><span class="shape-name text-xs">Retrig</span></div>',
        '    <div class="shape-led-row trigger-led-row" data-val="2" data-param="trigger_mode"><div class="led-dot"></div><span class="shape-name text-xs">Legato</span></div>',
        '    <div class="shape-led-row trigger-led-row" data-val="3" data-param="trigger_mode"><div class="led-dot"></div><span class="shape-name text-xs">One-Shot</span></div>',
        '</div>',
        '',
        '<div class="panel-section-title">Unison &amp; Drift Faders</div>',
        '<div class="panel-row" style="margin-top:5px;margin-bottom:5px">',
        '    <div class="ctrl-unit flex-col items-center" data-param="unison_detune" style="width:22%"><span class="label text-xs" style="margin-bottom:4px">Detune</span><div class="v-slider" style="height:80px"><div class="track"></div><div class="handle"></div></div></div>',
        '    <div class="ctrl-unit flex-col items-center" data-param="voice_drift" style="width:22%"><span class="label text-xs" style="margin-bottom:4px">Drift</span><div class="v-slider" style="height:80px"><div class="track"></div><div class="handle"></div></div></div>',
        '    <div class="ctrl-unit flex-col items-center" data-param="param_drift" style="width:22%"><span class="label text-xs" style="margin-bottom:4px">Par Drft</span><div class="v-slider" style="height:80px"><div class="track"></div><div class="handle"></div></div></div>',
        '    <div class="ctrl-unit flex-col items-center" data-param="drift_rate" style="width:22%"><span class="label text-xs" style="margin-bottom:4px">Drft Rate</span><div class="v-slider" style="height:80px"><div class="track"></div><div class="handle"></div></div></div>',
        '</div>'
    ].join('\n'); };

    NS.PORTA = function () { return [
        '<div class="panel-section-title">Portamento Mode</div>',
        '<div class="w-full" style="margin-bottom:8px">',
        '    <span class="label text-xs text-dim" style="display:block;margin-bottom:2px">PORTA MODE</span>',
        '    <div class="shape-selector-container" style="display:grid;grid-template-columns:repeat(2,1fr);gap:2px">',
        '        <div class="shape-led-row porta-mode-led-row" data-val="0"><div class="led-dot"></div><span class="shape-name" style="font-size:8px">Normal</span></div>',
        '        <div class="shape-led-row porta-mode-led-row" data-val="1"><div class="led-dot"></div><span class="shape-name" style="font-size:8px">Fingered</span></div>',
        '        <div class="shape-led-row porta-mode-led-row" data-val="2"><div class="led-dot"></div><span class="shape-name" style="font-size:8px">Fix-Rate</span></div>',
        '        <div class="shape-led-row porta-mode-led-row" data-val="3"><div class="led-dot"></div><span class="shape-name" style="font-size:8px">Fix-Fing</span></div>',
        '        <div class="shape-led-row porta-mode-led-row" data-val="4"><div class="led-dot"></div><span class="shape-name" style="font-size:8px">Exp</span></div>',
        '        <div class="shape-led-row porta-mode-led-row" data-val="5"><div class="led-dot"></div><span class="shape-name" style="font-size:8px">Exp-Fing</span></div>',
        '        <div class="shape-led-row porta-mode-led-row" data-val="6"><div class="led-dot"></div><span class="shape-name" style="font-size:8px">Fixed+2</span></div>',
        '        <div class="shape-led-row porta-mode-led-row" data-val="7"><div class="led-dot"></div><span class="shape-name" style="font-size:8px">Fixed-2</span></div>',
        '        <div class="shape-led-row porta-mode-led-row" data-val="8"><div class="led-dot"></div><span class="shape-name" style="font-size:8px">Fixed+5</span></div>',
        '        <div class="shape-led-row porta-mode-led-row" data-val="9"><div class="led-dot"></div><span class="shape-name" style="font-size:8px">Fixed-5</span></div>',
        '    </div>',
        '</div>',
        '<div class="panel-section-title">Note Priority</div>',
        '<div class="shape-selector-container" style="display:grid;grid-template-columns:repeat(3,1fr);gap:2px;margin-bottom:8px">',
        '    <div class="shape-led-row note-priority-led-row" data-val="0" data-param="note_priority"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Lowest</span></div>',
        '    <div class="shape-led-row note-priority-led-row" data-val="1" data-param="note_priority"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Highest</span></div>',
        '    <div class="shape-led-row note-priority-led-row" data-val="2" data-param="note_priority"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Last</span></div>',
        '</div>',
        '<div class="panel-section-title">Trigger Mode</div>',
        '<div class="shape-selector-container" style="display:grid;grid-template-columns:repeat(2,1fr);gap:2px;margin-bottom:8px">',
        '    <div class="shape-led-row trigger-mode-led-row" data-val="0" data-param="trigger_mode"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Mono</span></div>',
        '    <div class="shape-led-row trigger-mode-led-row" data-val="1" data-param="trigger_mode"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Retrig</span></div>',
        '    <div class="shape-led-row trigger-mode-led-row" data-val="2" data-param="trigger_mode"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Legato</span></div>',
        '    <div class="shape-led-row trigger-mode-led-row" data-val="3" data-param="trigger_mode"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">One-Shot</span></div>',
        '</div>',
        '<div class="panel-section-title">Portamento / Tune Sliders</div>',
        '<div class="panel-row" style="margin-top:5px;margin-bottom:5px;justify-content:space-around">',
        '    <div class="ctrl-unit flex-col items-center" data-param="global_portamento" style="width:22%"><span class="label text-xs">Porta Time</span><div class="v-slider" style="height:70px"><div class="track"></div><div class="handle"></div></div></div>',
        '    <div class="ctrl-unit flex-col items-center" data-param="global_tune" style="width:22%"><span class="label text-xs">Tune</span><div class="v-slider" style="height:70px"><div class="track"></div><div class="handle"></div></div></div>',
        '    <div class="ctrl-unit flex-col items-center" data-param="transpose" style="width:22%"><span class="label text-xs">Transp</span><div class="v-slider" style="height:70px"><div class="track"></div><div class="handle"></div></div></div>',
        '    <div class="ctrl-unit flex-col items-center" data-param="porta_osc_bal" style="width:22%"><span class="label text-xs">Osc Bal</span><div class="v-slider" style="height:70px"><div class="track"></div><div class="handle"></div></div></div>',
        '</div>',
        '<div class="panel-section-title">Pitch Bend Range</div>',
        '<div class="panel-row" style="margin-top:5px;margin-bottom:5px;justify-content:space-around">',
        '    <div class="ctrl-unit flex-col items-center" data-param="pitch_bend_up" style="width:45%"><span class="label text-xs">Bend Up</span><div class="v-slider" style="height:70px"><div class="track"></div><div class="handle"></div></div></div>',
        '    <div class="ctrl-unit flex-col items-center" data-param="pitch_bend_down" style="width:45%"><span class="label text-xs">Bend Down</span><div class="v-slider" style="height:70px"><div class="track"></div><div class="handle"></div></div></div>',
        '</div>'
    ].join('\n'); };
})();
