/**
 * @purpose Panel templates: Chord Memory (CHORD) and Poly Chord (POLY_CHORD).
 *          Appends to window.PANEL_TEMPLATES (initialized by panel_templates.js).
 * @classification UI/Templates
 */

(function () {
    const NS = window.PANEL_TEMPLATES = window.PANEL_TEMPLATES || {};

    NS.CHORD = function () { return [
        '<div class="panel-section-title">Chord Memory Status</div>',
        '<div class="flex-row justify-center w-full" style="margin-bottom:12px">',
        '    <div class="toggle-box" id="panel-chord-enable-box" data-param="chord_enable" style="width:80%" data-ctrl-tooltip="Chord Memory — one-touch chord playback"><span class="toggle-label">Chord Memory</span><div class="toggle-led"></div></div>',
        '</div>',
        '<div class="panel-section-title">Root Key</div>',
        '<div class="shape-selector-container" style="display:grid;grid-template-columns:repeat(4,1fr);gap:4px;margin-bottom:8px">',
        '    <div class="shape-led-row chord-key-led-row" data-val="0"><div class="led-dot"></div><span class="shape-name">C</span></div>',
        '    <div class="shape-led-row chord-key-led-row" data-val="1"><div class="led-dot"></div><span class="shape-name">C#</span></div>',
        '    <div class="shape-led-row chord-key-led-row" data-val="2"><div class="led-dot"></div><span class="shape-name">D</span></div>',
        '    <div class="shape-led-row chord-key-led-row" data-val="3"><div class="led-dot"></div><span class="shape-name">D#</span></div>',
        '    <div class="shape-led-row chord-key-led-row" data-val="4"><div class="led-dot"></div><span class="shape-name">E</span></div>',
        '    <div class="shape-led-row chord-key-led-row" data-val="5"><div class="led-dot"></div><span class="shape-name">F</span></div>',
        '    <div class="shape-led-row chord-key-led-row" data-val="6"><div class="led-dot"></div><span class="shape-name">F#</span></div>',
        '    <div class="shape-led-row chord-key-led-row" data-val="7"><div class="led-dot"></div><span class="shape-name">G</span></div>',
        '    <div class="shape-led-row chord-key-led-row" data-val="8"><div class="led-dot"></div><span class="shape-name">G#</span></div>',
        '    <div class="shape-led-row chord-key-led-row" data-val="9"><div class="led-dot"></div><span class="shape-name">A</span></div>',
        '    <div class="shape-led-row chord-key-led-row" data-val="10"><div class="led-dot"></div><span class="shape-name">A#</span></div>',
        '    <div class="shape-led-row chord-key-led-row" data-val="11"><div class="led-dot"></div><span class="shape-name">B</span></div>',
        '</div>',
        '<div class="panel-section-title">Chord Type</div>',
        '<div class="shape-selector-container" style="display:grid;grid-template-columns:repeat(2,1fr);gap:4px;margin-bottom:8px">',
        '    <div class="shape-led-row chord-type-led-row" data-val="0"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Memory</span></div>',
        '    <div class="shape-led-row chord-type-led-row" data-val="1"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Major</span></div>',
        '    <div class="shape-led-row chord-type-led-row" data-val="2"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Minor</span></div>',
        '    <div class="shape-led-row chord-type-led-row" data-val="3"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Major 7th</span></div>',
        '    <div class="shape-led-row chord-type-led-row" data-val="4"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Minor 7th</span></div>',
        '    <div class="shape-led-row chord-type-led-row" data-val="5"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Dom 7th</span></div>',
        '    <div class="shape-led-row chord-type-led-row" data-val="6"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Susp 4th</span></div>',
        '    <div class="shape-led-row chord-type-led-row" data-val="7"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Power Chd</span></div>',
        '    <div class="shape-led-row chord-type-led-row" data-val="8"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Aug</span></div>',
        '    <div class="shape-led-row chord-type-led-row" data-val="9"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Dim</span></div>',
        '    <div class="shape-led-row chord-type-led-row" data-val="10"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">Sus2</span></div>',
        '    <div class="shape-led-row chord-type-led-row" data-val="11"><div class="led-dot"></div><span class="shape-name" style="font-size:9px">7th</span></div>',
        '</div>',
        '<div class="panel-section-title" style="margin-top:10px">Hardware Connection</div>',
        '<div class="flex-row gap-8 w-full" style="margin-bottom:8px">',
        '    <button id="panel-chord-load-btn" class="modal-btn" style="flex:1;font-size:9px;padding:5px;background:var(--bg-hover);border-color:var(--border-dim)" data-ctrl-tooltip="Load Chord Memory from hardware DeepMind 12">Load from HW</button>',
        '    <button id="panel-chord-send-btn" class="modal-btn" style="flex:1;font-size:9px;padding:5px;background:var(--bg-hover);border-color:var(--border-dim)" data-ctrl-tooltip="Send Chord Memory to hardware DeepMind 12">Send to HW</button>',
        '</div>'
    ].join('\n'); };

    NS.POLY_CHORD = function () { return [
        '<div class="panel-section-title">Poly Chord Status</div>',
        '<div class="flex-row justify-center w-full" style="margin-bottom:12px">',
        '    <div class="toggle-box" id="panel-poly-chord-enable-box" data-param="poly_chord_enable" style="width:80%" data-ctrl-tooltip="Poly Chord — polyphonic chord memory"><span class="toggle-label">Poly Chord</span><div class="toggle-led"></div></div>',
        '</div>',
        '<div class="w-full" style="margin-bottom:4px">',
        '    <span class="label text-xs text-dim" style="display:block;margin-bottom:4px">SELECT KEY TO ASSIGN:</span>',
        '    <div class="shape-selector-container" style="display:grid;grid-template-columns:repeat(6,1fr);gap:3px;margin-bottom:6px">',
        '        <div class="shape-led-row poly-key-select-row" data-keyidx="0" style="padding:3px 2px"><span class="shape-name" style="font-size:9px">C</span></div>',
        '        <div class="shape-led-row poly-key-select-row" data-keyidx="1" style="padding:3px 2px"><span class="shape-name" style="font-size:9px">C#</span></div>',
        '        <div class="shape-led-row poly-key-select-row" data-keyidx="2" style="padding:3px 2px"><span class="shape-name" style="font-size:9px">D</span></div>',
        '        <div class="shape-led-row poly-key-select-row" data-keyidx="3" style="padding:3px 2px"><span class="shape-name" style="font-size:9px">D#</span></div>',
        '        <div class="shape-led-row poly-key-select-row" data-keyidx="4" style="padding:3px 2px"><span class="shape-name" style="font-size:9px">E</span></div>',
        '        <div class="shape-led-row poly-key-select-row" data-keyidx="5" style="padding:3px 2px"><span class="shape-name" style="font-size:9px">F</span></div>',
        '        <div class="shape-led-row poly-key-select-row" data-keyidx="6" style="padding:3px 2px"><span class="shape-name" style="font-size:9px">F#</span></div>',
        '        <div class="shape-led-row poly-key-select-row" data-keyidx="7" style="padding:3px 2px"><span class="shape-name" style="font-size:9px">G</span></div>',
        '        <div class="shape-led-row poly-key-select-row" data-keyidx="8" style="padding:3px 2px"><span class="shape-name" style="font-size:9px">G#</span></div>',
        '        <div class="shape-led-row poly-key-select-row" data-keyidx="9" style="padding:3px 2px"><span class="shape-name" style="font-size:9px">A</span></div>',
        '        <div class="shape-led-row poly-key-select-row" data-keyidx="10" style="padding:3px 2px"><span class="shape-name" style="font-size:9px">A#</span></div>',
        '        <div class="shape-led-row poly-key-select-row" data-keyidx="11" style="padding:3px 2px"><span class="shape-name" style="font-size:9px">B</span></div>',
        '    </div>',
        '</div>',
        '<div class="w-full" style="background:var(--bg-deepest);border:1px solid var(--border-dim);border-radius:var(--radius-sm);padding:8px;margin-bottom:8px">',
        '    <span class="label text-xs" style="display:block;margin-bottom:4px;color:var(--accent-blue)">ASSIGNED CHORD FOR KEY: <span id="poly-selected-key-label">C</span></span>',
        '    <div style="margin-bottom:4px">',
        '        <span class="label text-xs text-dim" style="display:block;margin-bottom:2px">ROOT KEY</span>',
        '        <div class="shape-selector-container" id="poly-assign-root-keys" style="display:grid;grid-template-columns:repeat(6,1fr);gap:2px">',
        '            <div class="shape-led-row poly-root-row" data-val="0" style="padding:2px 0;font-size:8px">C</div>',
        '            <div class="shape-led-row poly-root-row" data-val="1" style="padding:2px 0;font-size:8px">C#</div>',
        '            <div class="shape-led-row poly-root-row" data-val="2" style="padding:2px 0;font-size:8px">D</div>',
        '            <div class="shape-led-row poly-root-row" data-val="3" style="padding:2px 0;font-size:8px">D#</div>',
        '            <div class="shape-led-row poly-root-row" data-val="4" style="padding:2px 0;font-size:8px">E</div>',
        '            <div class="shape-led-row poly-root-row" data-val="5" style="padding:2px 0;font-size:8px">F</div>',
        '            <div class="shape-led-row poly-root-row" data-val="6" style="padding:2px 0;font-size:8px">F#</div>',
        '            <div class="shape-led-row poly-root-row" data-val="7" style="padding:2px 0;font-size:8px">G</div>',
        '            <div class="shape-led-row poly-root-row" data-val="8" style="padding:2px 0;font-size:8px">G#</div>',
        '            <div class="shape-led-row poly-root-row" data-val="9" style="padding:2px 0;font-size:8px">A</div>',
        '            <div class="shape-led-row poly-root-row" data-val="10" style="padding:2px 0;font-size:8px">A#</div>',
        '            <div class="shape-led-row poly-root-row" data-val="11" style="padding:2px 0;font-size:8px">B</div>',
        '        </div>',
        '    </div>',
        '    <div>',
        '        <span class="label text-xs text-dim" style="display:block;margin-bottom:2px">CHORD TYPE</span>',
        '        <div class="shape-selector-container" id="poly-assign-chord-types" style="display:grid;grid-template-columns:repeat(4,1fr);gap:2px">',
        '            <div class="shape-led-row poly-type-row" data-val="0" style="padding:2px 0;font-size:8px">Memory</div>',
        '            <div class="shape-led-row poly-type-row" data-val="1" style="padding:2px 0;font-size:8px">Major</div>',
        '            <div class="shape-led-row poly-type-row" data-val="2" style="padding:2px 0;font-size:8px">Minor</div>',
        '            <div class="shape-led-row poly-type-row" data-val="3" style="padding:2px 0;font-size:8px">Maj7</div>',
        '            <div class="shape-led-row poly-type-row" data-val="4" style="padding:2px 0;font-size:8px">Min7</div>',
        '            <div class="shape-led-row poly-type-row" data-val="5" style="padding:2px 0;font-size:8px">Dom7</div>',
        '            <div class="shape-led-row poly-type-row" data-val="6" style="padding:2px 0;font-size:8px">Sus4</div>',
        '            <div class="shape-led-row poly-type-row" data-val="7" style="padding:2px 0;font-size:8px">Pwr</div>',
        '            <div class="shape-led-row poly-type-row" data-val="8" style="padding:2px 0;font-size:8px">Aug</div>',
        '            <div class="shape-led-row poly-type-row" data-val="9" style="padding:2px 0;font-size:8px">Dim</div>',
        '            <div class="shape-led-row poly-type-row" data-val="10" style="padding:2px 0;font-size:8px">Sus2</div>',
        '            <div class="shape-led-row poly-type-row" data-val="11" style="padding:2px 0;font-size:8px">7th</div>',
        '        </div>',
        '    </div>',
        '</div>',
        '<div class="panel-section-title">Summary (all keys)</div>',
        '<div id="poly-chord-summary" style="display:grid;grid-template-columns:repeat(4,1fr);gap:2px;margin-bottom:8px">',
        '    <div style="font-size:7px;color:var(--text-dim);padding:2px">C: Major</div>',
        '    <div style="font-size:7px;color:var(--text-dim);padding:2px">C#: Minor</div>',
        '    <div style="font-size:7px;color:var(--text-dim);padding:2px">D: Major</div>',
        '    <div style="font-size:7px;color:var(--text-dim);padding:2px">D#: Minor</div>',
        '    <div style="font-size:7px;color:var(--text-dim);padding:2px">E: Major</div>',
        '    <div style="font-size:7px;color:var(--text-dim);padding:2px">F: Minor</div>',
        '    <div style="font-size:7px;color:var(--text-dim);padding:2px">F#: Major</div>',
        '    <div style="font-size:7px;color:var(--text-dim);padding:2px">G: Minor</div>',
        '    <div style="font-size:7px;color:var(--text-dim);padding:2px">G#: Major</div>',
        '    <div style="font-size:7px;color:var(--text-dim);padding:2px">A: Minor</div>',
        '    <div style="font-size:7px;color:var(--text-dim);padding:2px">A#: Major</div>',
        '    <div style="font-size:7px;color:var(--text-dim);padding:2px">B: Minor</div>',
        '</div>',
        '<div class="panel-section-title" style="margin-top:4px">Presets &amp; Hardware</div>',
        '<div class="flex-row gap-6 w-full" style="margin-bottom:8px;flex-wrap:wrap">',
        '    <button id="panel-polychord-defaults-btn" class="modal-btn" style="flex:1;font-size:9px;padding:4px;background:var(--bg-hover);border-color:var(--border-dim)" data-ctrl-tooltip="Reset all keys to default Major/Minor pattern">Reset Defaults</button>',
        '    <button id="panel-polychord-load-btn" class="modal-btn" style="flex:1;font-size:9px;padding:4px;background:var(--bg-hover);border-color:var(--border-dim)" data-ctrl-tooltip="Load Poly Chord from hardware DeepMind 12">Load HW</button>',
        '    <button id="panel-polychord-send-btn" class="modal-btn" style="flex:1;font-size:9px;padding:4px;background:var(--bg-hover);border-color:var(--border-dim)" data-ctrl-tooltip="Send Poly Chord to hardware DeepMind 12">Send HW</button>',
        '</div>'
    ].join('\n'); };
})();
