#!/usr/bin/env node
/**
 * registry_generator.js — Fase 1 · Esquema Declarativo y Generador Versionado
 * ===========================================================================
 * Fusiona las TRES fuentes de verdad de parámetros de ABDEep y emite los
 * artefactos .gen (JS + C++ + data.json) bajo el esquema schemaVersion 1.
 *
 *   Fuentes:
 *     1. WebUI/js/bridge-param-maps.js      → PARAM_TO_BYTE_OFFSET / PARAM_TO_CC /
 *                                             BIPOLAR_BYTES / ENUM_BYTES (canónico hardware)
 *     2. WebUI/js/byte_map_data.js          → BYTE_MAP (242 bytes físicos, display names,
 *                                             regiones, tipos descriptivos, descripciones)
 *     3. resources/parameters_spec.json     → metadatos legacy del emulador (name, default,
 *                                             min/max, options, description, midi_cc)
 *
 *   Artefactos emitidos (todos versionados en el repo):
 *     - schemas/parameter-registry.data.json        (instancia canónica validada)
 *     - WebUI/js/registry.gen.js                    (registro JS para la WebUI)
 *     - Source/Core/ParameterRegistry.gen.h         (registro C++ — enum + array + lookups)
 *     - Source/Core/ParameterRegistry.gen.cpp
 *
 *   Política de validación:
 *     - Errores FATALES (exit 1, no emite nada): ids duplicados, rangos incompatibles
 *       (min>=max), offsets fuera de 0..399, byte map no contiguo, colisiones de
 *       identificador C++ (cppName), ids sin byte offset en el mapa bridge, y
 *       parámetros físicos en regiones reservadas del preset (223-238 nombre del
 *       patch, 239-241 cola del payload) — RESERVED_BYTE_COLLISION.
 *     - Advertencias (exit 0, se registran en warnings[]): divergencias CC legacy vs
 *       canónico (comparisonMode, §6 del plan) y parámetros spec-only.
 *
 *   Uso:
 *     node scripts/registry_generator.js
 *   Enlazado desde:
 *     scripts/validate_and_generate.ps1 (entrada humana/CI)
 *     CMakeLists.txt  (add_custom_command de regeneración)
 *
 * Exit code: 0 = OK (con o sin warnings), 1 = errores fatales.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');

// ── Rutas de fuentes ──────────────────────────────────────────────
const SRC = {
  bridge: path.join(ROOT, 'WebUI', 'js', 'bridge-param-maps.js'),
  byteMap: path.join(ROOT, 'WebUI', 'js', 'byte_map_data.js'),
  spec: path.join(ROOT, 'resources', 'parameters_spec.json'),
  schema: path.join(ROOT, 'schemas', 'parameter-registry.json'),
};

// ── Rutas de artefactos ───────────────────────────────────────────
const OUT = {
  data: path.join(ROOT, 'schemas', 'parameter-registry.data.json'),
  js: path.join(ROOT, 'WebUI', 'js', 'registry.gen.js'),
  h: path.join(ROOT, 'Source', 'Core', 'ParameterRegistry.gen.h'),
  cpp: path.join(ROOT, 'Source', 'Core', 'ParameterRegistry.gen.cpp'),
};

const GEN_HEADER_JS = '/* AUTO-GENERATED by scripts/validate_and_generate.ps1 → registry_generator.js — DO NOT EDIT. */';
const GEN_HEADER_CPP = '// AUTO-GENERATED by scripts/validate_and_generate.ps1 → registry_generator.js — DO NOT EDIT.';

// ── Colección de problemas ────────────────────────────────────────
const fatalErrors = [];
const warnings = [];

const fail = (code, message) => fatalErrors.push({ code, message });
const warn = (code, message) => warnings.push({ code, message });

// ── Helpers ───────────────────────────────────────────────────────
function sha256(text) {
  return crypto.createHash('sha256').update(text).digest('hex');
}

function loadJsGlobal(file) {
  // Los scripts del WebUI se asignan a window.X. Se ejecutan en un sandbox
  // para obtener su export sin tocar el global del proceso.
  const code = fs.readFileSync(file, 'utf8');
  const sandbox = { window: {} };
  const fn = new Function('window', code + '\n;return window;');
  return fn(sandbox.window);
}

/** 'lfo1_rate' → 'Lfo1Rate', 'fx1_param10' → 'Fx1Param10' */
function toPascalCase(id) {
  return id.split(/[^A-Za-z0-9]+/).filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

// ── 1. Cargar fuentes ─────────────────────────────────────────────
let bridge, byteMap, spec;
try {
  const bridgeWin = loadJsGlobal(SRC.bridge);
  bridge = bridgeWin.BRIDGE_PARAM_MAPS;
  if (!bridge) {fail('SRC_BRIDGE_MISSING', 'bridge-param-maps.js no expuso window.BRIDGE_PARAM_MAPS');}
} catch (e) {
  fail('SRC_BRIDGE_LOAD', 'No se pudo cargar bridge-param-maps.js: ' + e.message);
}
try {
  const byteWin = loadJsGlobal(SRC.byteMap);
  byteMap = byteWin.BYTE_MAP;
  if (!byteMap) {fail('SRC_BYTEMAP_MISSING', 'byte_map_data.js no expuso window.BYTE_MAP');}
} catch (e) {
  fail('SRC_BYTEMAP_LOAD', 'No se pudo cargar byte_map_data.js: ' + e.message);
}
try {
  const raw = JSON.parse(fs.readFileSync(SRC.spec, 'utf8'));
  spec = raw && raw.parameters ? raw.parameters : raw;
  if (!Array.isArray(spec)) {fail('SRC_SPEC_SHAPE', 'parameters_spec.json no contiene un array en "parameters"');}
} catch (e) {
  fail('SRC_SPEC_LOAD', 'No se pudo cargar parameters_spec.json: ' + e.message);
}
if (fatalErrors.length > 0) {
  reportAndExit(1);
}

const sourceHashes = {
  parametersSpec: sha256(fs.readFileSync(SRC.spec, 'utf8')),
  bridgeParamMaps: sha256(fs.readFileSync(SRC.bridge, 'utf8')),
  byteMapData: sha256(fs.readFileSync(SRC.byteMap, 'utf8')),
};

// ── 2. Validación estructural del byte map ────────────────────────
if (!Array.isArray(byteMap) || byteMap.length !== 242) {
  fail('BYTEMAP_LENGTH', 'BYTE_MAP debe tener 242 entradas (físicas); tiene ' + (byteMap ? byteMap.length : 'n/a'));
} else {
  byteMap.forEach((entry, idx) => {
    if (!entry || entry.idx !== idx) {
      fail('BYTEMAP_CONTIGUITY', 'BYTE_MAP[' + idx + '] no es contiguo (idx=' + (entry && entry.idx) + ')');
    }
    if (!entry.param || !entry.region || !entry.type) {
      fail('BYTEMAP_FIELDS', 'BYTE_MAP[' + idx + '] carece de param/region/type');
    }
  });
}

// ── 3. Fusionar fuentes ───────────────────────────────────────────
const paramToOffset = bridge.PARAM_TO_BYTE_OFFSET || {};
const paramToCC = bridge.PARAM_TO_CC || {};
const enumBytes = bridge.ENUM_BYTES || {};
const bipolarBytes = bridge.BIPOLAR_BYTES instanceof Set ? bridge.BIPOLAR_BYTES : new Set(Object.keys(bridge.BIPOLAR_BYTES || {}).map(Number));

const specById = new Map();
for (const p of spec) {specById.set(p.id, p);}

const entries = [];
const byOffset = {}; // byteOffset → [ids]

for (const [id, offsetRaw] of Object.entries(paramToOffset)) {
  const byteOffset = Number(offsetRaw);
  if (!Number.isInteger(byteOffset) || byteOffset < 0 || byteOffset > 399) {
    fail('OFFSET_RANGE', 'Param "' + id + '" tiene byteOffset inválido: ' + offsetRaw);
    continue;
  }
  (byOffset[byteOffset] = byOffset[byteOffset] || []).push(id);
}

// Validar offsets con múltiples ids. Los grupos {32, 88, 160} son alias
// INTENCIONALES documentados en el bridge; cualquier grupo nuevo sería una
// colisión NRPN real y se rechaza (política §1.1: NRPNs colisionados).
const kKnownAliasOffsets = new Set([32, 88, 160]);
for (const [off, ids] of Object.entries(byOffset)) {
  if (ids.length > 1 && !kKnownAliasOffsets.has(Number(off))) {
    fail('NRPN_COLLISION', 'Offset ' + off + ' compartido sin alias declarado: ' + ids.join(', '));
  }
}

// ── 3b. Regiones reservadas del preset (NO admite parámetros) ─────
// El preset físico DM12 no tiene bytes editables más allá de 222:
//   - 223-238  → nombre del patch (15-16 chars ASCII; verificado en dumps reales:
//                banco A preset 0 = "Blue Dolphin BC " empieza en el byte 223)
//   - 239-241  → cola del payload empaquetado
// Cualquier parámetro físico que aterrice aquí es un error FATAL (usurparía
// bytes del nombre del patch); los parámetros del emulador sin byte físico
// deben declararse en la región virtual (>=300), p.ej. fx_feedback_gain=300,
// fx_send_level=301.
const kReservedPhysicalRegions = [
  { start: 223, end: 238, label: 'patch name (223-238)' },
  { start: 239, end: 241, label: 'payload tail (239-241)' },
];
for (const [id, offsetRaw] of Object.entries(paramToOffset)) {
  const byteOffset = Number(offsetRaw);
  if (!Number.isInteger(byteOffset) || byteOffset < 0) {continue;}
  if (byteOffset > 241) {continue;} // solo aplica a bytes físicos 0-241
  const region = kReservedPhysicalRegions.find((r) => byteOffset >= r.start && byteOffset <= r.end);
  if (region) {
    fail('RESERVED_BYTE_COLLISION', 'Param "' + id + '" (byteOffset=' + byteOffset +
      ') cae en la región reservada ' + region.label + ' — sin byte físico legítimo; mover a virtual (>=300)');
  }
}

// Construir entrada canónica por id (mantener orden de definición del bridge).
for (const [id, offsetRaw] of Object.entries(paramToOffset)) {
  const byteOffset = Number(offsetRaw);
  const specMeta = specById.get(id);

  // Regla 1.1: rangos incompatibles en la fuente legacy.
  if (specMeta && typeof specMeta.min === 'number' && typeof specMeta.max === 'number' && specMeta.min >= specMeta.max) {
    fail('RANGE_INCOMPATIBLE', 'Spec "' + id + '": min(' + specMeta.min + ') >= max(' + specMeta.max + ')');
    continue;
  }

  const category = byteOffset >= 300 ? 'virtual' : (byteOffset >= 242 ? 'extended' : 'physical');
  const isEnum = Object.prototype.hasOwnProperty.call(enumBytes, String(byteOffset));
  const isBipolar = bipolarBytes.has(byteOffset);
  const codecType = isEnum ? 'enum' : (isBipolar ? 'bipolar' : 'value');

  const bm = category === 'physical' && byteMap[byteOffset] ? byteMap[byteOffset] : null;
  const cc = paramToCC[id] !== undefined ? Number(paramToCC[id]) : null;
  const legacyCC = specMeta && specMeta.midi_cc !== undefined ? Number(specMeta.midi_cc) : null;
  const ccConflict = cc !== null && legacyCC !== null && cc !== legacyCC;
  if (ccConflict) {
    warn('CC_LEGACY_DIVERGENCE', 'Param "' + id + '": CC canónico=' + cc + ' vs legacy=' + legacyCC + ' (comparisonMode)');
  }

  const enumMax = isEnum ? Number(enumBytes[String(byteOffset)]) : null;
  if (isEnum && (!Number.isInteger(enumMax) || enumMax < 1)) {
    fail('ENUM_MAX', 'Param "' + id + '" enum con ENUM_BYTES inválido: ' + enumMax);
    continue;
  }

  const aliases = (byOffset[byteOffset] || []).filter((a) => a !== id);
  const cppName = toPascalCase(id);

  entries.push({
    id,
    byteOffset,
    category,
    region: bm ? bm.region : (category === 'extended' ? 'Extended' : 'Virtual'),
    codecType,
    byteMapType: bm ? bm.type : null,
    enumMax,
    enumLabels: bm && bm.enumLabels ? bm.enumLabels : null,
    cc,
    legacyCC,
    ccConflict,
    name: (specMeta && specMeta.name) || (bm && bm.param) || null,
    desc: (specMeta && specMeta.description) || (bm && bm.desc) || null,
    defaultValue: computeDefaultNormalized(specMeta),
    aliases,
    cppName,
    index: 0, // se asigna tras ordenar
  });
}

// Regla: ids sin byte offset válido o duplicados de cppName.
const cppNames = new Map();
entries.forEach((e, idx) => {
  e.index = idx;
  if (cppNames.has(e.cppName)) {
    fail('CPP_NAME_COLLISION', 'cppName "' + e.cppName + '" colisiona entre "' + cppNames.get(e.cppName) + '" y "' + e.id + '"');
  }
  cppNames.set(e.cppName, e.id);
});

// Parámetros spec-only (universo legacy sin byte físico).
const specOnly = [];
for (const p of spec) {
  if (!paramToOffset[p.id]) {
    specOnly.push({
      id: p.id,
      name: p.name || null,
      block: p.block || null,
      type: p.type || null,
      description: p.description || null,
      options: p.options || null,
    });
  }
}

// byteMap canónico: los 242 bytes con su id de registro (o null).
const canonicalByteMap = byteMap.map((bmEntry) => {
  const ids = byOffset[bmEntry.idx] || null;
  return {
    idx: bmEntry.idx,
    param: bmEntry.param,
    region: bmEntry.region,
    type: bmEntry.type,
    desc: bmEntry.desc || null,
    enumLabels: bmEntry.enumLabels || null,
    id: ids && ids.length > 0 ? ids[0] : null,
  };
});

// ── 4. Resumen ────────────────────────────────────────────────────
const aliasGroups = Object.values(byOffset).filter((ids) => ids.length > 1).length;
const summary = {
  total: entries.length,
  physical: entries.filter((e) => e.category === 'physical').length,
  extended: entries.filter((e) => e.category === 'extended').length,
  virtual: entries.filter((e) => e.category === 'virtual').length,
  aliasGroups,
  enumCount: entries.filter((e) => e.codecType === 'enum').length,
  bipolarCount: entries.filter((e) => e.codecType === 'bipolar').length,
  valueCount: entries.filter((e) => e.codecType === 'value').length,
  ccCount: entries.filter((e) => e.cc !== null).length,
  specOnlyCount: specOnly.length,
  warningCount: warnings.length,
};

// ── 5. Emitir si no hay errores fatales ───────────────────────────
if (fatalErrors.length > 0) {reportAndExit(1);}

const registry = {
  schemaVersion: 1,
  generatedAt: new Date().toISOString(),
  sourceHashes,
  parameters: entries,
  byteMap: canonicalByteMap,
  specOnly,
  warnings,
  summary,
};

// Emisión atómica: escribir a .tmp + rename para que un fallo a mitad de la
// generación nunca deje artefactos parciales que CMake considere vigentes.
const payloads = [
  [OUT.data, JSON.stringify(registry, null, 2) + '\n'],
  [OUT.js, renderJs(registry)],
  [OUT.h, renderCppHeader(registry)],
  [OUT.cpp, renderCppSource(registry)],
];
for (const [file, content] of payloads) {writeAtomic(file, content);}

// Post-emisión: re-validar la instancia emitida contra las invariantes clave
// del esquema (sin dependencia externa; ajv llegará en el job CI de Fase 7).
const emitted = JSON.parse(fs.readFileSync(OUT.data, 'utf8'));
validateEmitted(emitted);

// ── 6. Reporte ────────────────────────────────────────────────────
console.log('[registry] OK — schemaVersion=1 · parámetros=' + summary.total +
  ' (físicos=' + summary.physical + ' · extendidos=' + summary.extended + ' · virtuales=' + summary.virtual + ')' +
  ' · byteMap=242 · aliasGroups=' + summary.aliasGroups +
  ' · enum=' + summary.enumCount + ' · bipolar=' + summary.bipolarCount + ' · cc=' + summary.ccCount);
for (const w of warnings) {console.log('[registry] WARN  ' + w.code + ': ' + w.message);}
if (warnings.length > 0) {
  console.log('[registry] Warnings no fatales registrados en warnings[] (comparisonMode §6).');
}
console.log('[registry] Emitidos:');
for (const f of Object.values(OUT)) {console.log('  - ' + path.relative(ROOT, f));}
process.exit(0);

// ── Implementaciones auxiliares ───────────────────────────────────
function writeAtomic(file, content) {
  const tmp = file + '.tmp';
  fs.writeFileSync(tmp, content);
  fs.renameSync(tmp, file);
}

// Valida la instancia emitida contra invariantes del esquema (espejo de lo que
// validará el job CI schema-validation con ajv en Fase 7).
function validateEmitted(d) {
  if (d.schemaVersion !== 1) {fail('SCHEMA_VERSION', 'data.json no tiene schemaVersion=1');}
  if (!Array.isArray(d.parameters) || d.parameters.length !== entries.length) {
    fail('EMITTED_PARAMETERS', 'data.json parámetros no coinciden con la generación');
  }
  if (!Array.isArray(d.byteMap) || d.byteMap.length !== 242) {
    fail('EMITTED_BYTEMAP', 'data.json byteMap ≠ 242');
  }
  const cpp = new Set();
  for (const p of d.parameters) {
    if (!/^[A-Z][A-Za-z0-9]*$/.test(p.cppName)) {fail('EMITTED_CPPNAME', 'cppName inválido: ' + p.id);}
    if (cpp.has(p.cppName)) {fail('EMITTED_CPPNAME_DUP', 'cppName duplicado: ' + p.cppName);}
    cpp.add(p.cppName);
  }
  if (fatalErrors.length > 0) {reportAndExit(1);}
}

function computeDefaultNormalized(specMeta) {
  if (!specMeta) {return null;}
  if (specMeta.type === 'bool') {return specMeta.default === true ? 1 : (specMeta.default === false ? 0 : null);}
  if (typeof specMeta.default === 'number') {
    if (typeof specMeta.min === 'number' && typeof specMeta.max === 'number' && specMeta.max > specMeta.min) {
      const n = (specMeta.default - specMeta.min) / (specMeta.max - specMeta.min);
      return Math.min(1, Math.max(0, n));
    }
    return Math.min(1, Math.max(0, specMeta.default));
  }
  if (specMeta.type === 'enum' && Array.isArray(specMeta.options) && typeof specMeta.default === 'string') {
    const idx = specMeta.options.indexOf(specMeta.default);
    if (idx >= 0 && specMeta.options.length > 1) {return idx / (specMeta.options.length - 1);}
  }
  return null;
}

function reportAndExit(code) {
  console.error('[registry] ERRORES FATALES — no se emiten artefactos:');
  for (const e of fatalErrors) {console.error('  ✗ ' + e.code + ': ' + e.message);}
  process.exit(code);
}

// ── Render JS (UMD: window.ParameterRegistry + module.exports) ────
function renderJs(reg) {
  const lines = [];
  lines.push(GEN_HEADER_JS);
  lines.push('/* eslint-disable */');
  lines.push('(function (root, factory) {');
  lines.push('  if (typeof module === "object" && module.exports) { module.exports = factory(); }');
  lines.push('  else if (typeof window !== "undefined") { window.ParameterRegistry = factory(); }');
  lines.push('  else { root.ParameterRegistry = factory(); }');
  lines.push('})(typeof self !== "undefined" ? self : this, function () {');
  lines.push('  var byId = {};');
  lines.push('  var byOffset = {};');
  lines.push('  var parameters = ' + JSON.stringify(reg.parameters) + ';');
  lines.push('');
  lines.push('  parameters.forEach(function (p) { byId[p.id] = p; });');
  lines.push('  parameters.forEach(function (p) {');
  lines.push('    (byOffset[p.byteOffset] = byOffset[p.byteOffset] || []).push(p.id);');
  lines.push('  });');
  lines.push('');  lines.push('');
  lines.push('    return {');
  lines.push('    schemaVersion: 1,');
  lines.push('    generatedAt: ' + JSON.stringify(reg.generatedAt) + ',');
  lines.push('    sourceHashes: ' + JSON.stringify(reg.sourceHashes) + ',');
  lines.push('    parameters: parameters,');
  lines.push('    byteMap: ' + JSON.stringify(reg.byteMap) + ',');
  lines.push('    specOnly: ' + JSON.stringify(reg.specOnly) + ',');
  lines.push('    warnings: ' + JSON.stringify(reg.warnings) + ',');
  lines.push('    summary: ' + JSON.stringify(reg.summary) + ',');
  lines.push('    byId: byId,');
  lines.push('    byOffset: byOffset,');
  lines.push('    rawToNormalized: function (byteOffset, rawValue) {');
  lines.push('      if (byteOffset === undefined) return 0;');
  lines.push('      var p = byOffset[byteOffset] && byOffset[byteOffset][0] ? byId[byOffset[byteOffset][0]] : null;');
  lines.push('      if (p && p.codecType === "bipolar") { return Math.max(0, Math.min(1, ((rawValue - 128) / 127 + 1) / 2)); }');
  lines.push('      if (p && p.codecType === "enum" && p.enumMax) { return Math.min(1, rawValue / p.enumMax); }');
  lines.push('      return rawValue / 255;');
  lines.push('    },');
  lines.push('    normalizedToRaw: function (byteOffset, normalizedValue) {');
  lines.push('      var p = byOffset[byteOffset] && byOffset[byteOffset][0] ? byId[byOffset[byteOffset][0]] : null;');
  lines.push('      if (p && p.codecType === "bipolar") { return Math.round(((normalizedValue * 2 - 1) * 127) + 128); }');
  lines.push('      if (p && p.codecType === "enum" && p.enumMax) { return Math.round(normalizedValue * p.enumMax); }');
  lines.push('      return Math.round(normalizedValue * 255);');
  lines.push('    }');
  lines.push('  };');
  lines.push('});');
  lines.push('');
  return lines.join('\n');
}

// ── Render C++ ────────────────────────────────────────────────────
function codecTypeId(t) { return t === 'bipolar' ? 1 : (t === 'enum' ? 2 : 0); }

function renderCppHeader(reg) {
  const L = [];
  L.push(GEN_HEADER_CPP);
  L.push('#pragma once');
  L.push('');
  L.push('#include <array>');
  L.push('#include <cstdint>');
  L.push('#include <string_view>');
  L.push('');
  L.push('namespace ABD');
  L.push('{');
  L.push('namespace Registry');
  L.push('{');
  L.push('');
  L.push('// Índices generados en build-time (lookup O(1) por enum — invariante §3.2 del plan).');
  L.push('enum class ParameterIndex : std::uint16_t');
  L.push('{');
  reg.parameters.forEach((p) => L.push('    ' + p.cppName + ' = ' + p.index + ','));
  L.push('    kCount');
  L.push('};');
  L.push('');
  L.push('// codecType: 0 = value, 1 = bipolar, 2 = enum');
  L.push('struct ParameterEntry');
  L.push('{');
  L.push('    const char* id;');
  L.push('    std::uint16_t byteOffset;');
  L.push('    const char* region;');
  L.push('    std::uint8_t codecType;');
  L.push('    std::uint8_t cc;            // 0 = no mapeado');
  L.push('    std::uint8_t enumMax;       // 0 = n/a');
  L.push('    float defaultValue;         // normalized 0..1; -1.0f = desconocido');
  L.push('    ParameterIndex index;');
  L.push('};');
  L.push('');
  L.push('inline constexpr std::size_t kParameterCount = ' + reg.parameters.length + ';');
  L.push('inline constexpr std::size_t kByteMapSize = ' + reg.byteMap.length + ';');
  L.push('');
  L.push('extern const std::array<ParameterEntry, kParameterCount> kParameters;');
  L.push('extern const std::array<const char*, kByteMapSize> kByteMapParams;');
  L.push('');
  L.push('// Lookups para hilo de control / tests (nunca en el hilo de audio).');
  L.push('inline const ParameterEntry* findParameterById (std::string_view id) noexcept');
  L.push('{');
  L.push('    for (const auto& p : kParameters)');
  L.push('        if (id == p.id)');
  L.push('            return &p;');
  L.push('    return nullptr;');
  L.push('}');
  L.push('');
  L.push('inline const ParameterEntry* findParameterByOffset (std::uint16_t byteOffset) noexcept');
  L.push('{');
  L.push('    for (const auto& p : kParameters)');
  L.push('        if (byteOffset == p.byteOffset)');
  L.push('            return &p;');
  L.push('    return nullptr;');
  L.push('}');
  L.push('');
  L.push('} // namespace Registry');
  L.push('} // namespace ABD');
  L.push('');
  return L.join('\n');
}

function renderCppSource(reg) {
  const L = [];
  L.push(GEN_HEADER_CPP);
  L.push('#include "ParameterRegistry.gen.h"');
  L.push('');
  L.push('namespace ABD');
  L.push('{');
  L.push('namespace Registry');
  L.push('{');
  L.push('');
  L.push('const std::array<ParameterEntry, kParameterCount> kParameters = {{');
  reg.parameters.forEach((p) => {
    const def = p.defaultValue === null ? -1.0 : p.defaultValue;
    L.push('    { "' + p.id + '", ' + p.byteOffset + ', "' + p.region + '", ' + codecTypeId(p.codecType) +
      ', ' + (p.cc === null ? 0 : p.cc) + ', ' + (p.enumMax === null ? 0 : p.enumMax) +
      ', ' + def.toFixed(6) + 'f, ParameterIndex::' + p.cppName + ' },');
  });
  L.push('}};');
  L.push('');
  L.push('const std::array<const char*, kByteMapSize> kByteMapParams = {{');
  reg.byteMap.forEach((b) => L.push('    "' + escapeCpp(b.param) + '",'));
  L.push('}};');
  L.push('');
  L.push('} // namespace Registry');
  L.push('} // namespace ABD');
  L.push('');
  return L.join('\n');
}

function escapeCpp(s) {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
